### Decision Tree

#### Import Packages

In [1]:
%run ml_helpers.ipynb
%run ml.ipynb

       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
29557         108     1      1713        17       1  2018     1   First  1713
29558         109     1      1713        17       1  2018     1  Second  1713
29559         110     1      1713        17       1  2018     1   Third  1713
29560         111     1      1713        17       1  2018     2   Third  1713
29561         112     1      1713        17       1  2018     2   First  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
49256       59052     1       312         3       1  2019    11  Second   312
49257       59053     1       312         3       1  2019    11   Third   312
49258       59054     1       312         3       1  2019    12  Second   312
49259       59055     1       312         3       1  2019    12   First   312
49260       59056     1       312         3       1  2019    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
29557       8  ...               63.0         9.0             6.0
29558      16  ...               63.0         9.0             6.0
29559      24  ...               63.0         9.0             6.0
29560      16  ...               63.0         9.0             6.0
29561       8  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
49256      43  ...               14.0         1.0             3.0
49257      28  ...               14.0         1.0             3.0
49258      33  ...               14.0         1.0             3.0
49259      19  ...               14.0         1.0             3.0
49260      31  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
29557                  1.0              92.0     169276.405792
29558                  1.0              92.0     169276.405792
29559                  1.0              92.0     169276.405792
29560                  1.0              92.0     169276.405792
29561                  1.0              92.0     169276.405792
...                    ...               ...               ...
49256                  1.0              38.0     200633.844449
49257                  1.0              38.0     200633.844449
49258                  1.0              38.0     200633.844449
49259                  1.0              38.0     200633.844449
49260                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
29557      13283.675264    5454.068890       3258.006066             0.231076
29558      13283.675264    5454.068890       3258.006066             0.231076
29559      13283.675264    5454.068890       3258.006066             0.231076
29560      13283.675264    5454.068890       3258.006066             0.231076
29561      13283.675264    5454.068890       3258.006066             0.231076
...                 ...            ...               ...                  ...
49256       4144.689546    4843.037238       4374.482421             0.174216
49257       4144.689546    4843.037238       4374.482421             0.174216
49258       4144.689546    4843.037238       4374.482421             0.170732
49259       4144.689546    4843.037238       4374.482421             0.174216
49260       4144.689546    4843.037238       4374.482421             0.174216

[19704 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
19712          72     1      1713        17       1  2017     1   First  1713
19713          73     1      1713        17       1  2017     1   Third  1713
19714          74     1      1713        17       1  2017     1  Second  1713
19715          75     1      1713        17       1  2017     2  Second  1713
19716          76     1      1713        17       1  2017     2   Third  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
39402       59016     1       312         3       1  2018    11   Third   312
39403       59017     1       312         3       1  2018    11   First   312
39404       59018     1       312         3       1  2018    12   First   312
39405       59019     1       312         3       1  2018    12  Second   312
39406       59020     1       312         3       1  2018    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
19712      17  ...               63.0         9.0             6.0
19713      23  ...               63.0         9.0             6.0
19714      17  ...               63.0         9.0             6.0
19715      10  ...               63.0         9.0             6.0
19716      19  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
39402      33  ...               14.0         1.0             3.0
39403      12  ...               14.0         1.0             3.0
39404      15  ...               14.0         1.0             3.0
39405      36  ...               14.0         1.0             3.0
39406      34  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
19712                  1.0              92.0     169276.405792
19713                  1.0              92.0     169276.405792
19714                  1.0              92.0     169276.405792
19715                  1.0              92.0     169276.405792
19716                  1.0              92.0     169276.405792
...                    ...               ...               ...
39402                  1.0              38.0     200633.844449
39403                  1.0              38.0     200633.844449
39404                  1.0              38.0     200633.844449
39405                  1.0              38.0     200633.844449
39406                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
19712      13283.675264    5454.068890       3258.006066             0.243028
19713      13283.675264    5454.068890       3258.006066             0.243028
19714      13283.675264    5454.068890       3258.006066             0.243028
19715      13283.675264    5454.068890       3258.006066             0.243028
19716      13283.675264    5454.068890       3258.006066             0.243028
...                 ...            ...               ...                  ...
39402       4144.689546    4843.037238       4374.482421             0.104530
39403       4144.689546    4843.037238       4374.482421             0.104530
39404       4144.689546    4843.037238       4374.482421             0.104530
39405       4144.689546    4843.037238       4374.482421             0.101045
39406       4144.689546    4843.037238       4374.482421             0.104530

[19695 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
9861           36     1      1713        17       1  2016     1  Second  1713
9862           37     1      1713        17       1  2016     1   Third  1713
9863           38     1      1713        17       1  2016     1   First  1713
9864           39     1      1713        17       1  2016     2   First  1713
9865           40     1      1713        17       1  2016     2  Second  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
29552       58980     1       312         3       1  2017    11  Second   312
29553       58981     1       312         3       1  2017    11   Third   312
29554       58982     1       312         3       1  2017    12  Second   312
29555       58983     1       312         3       1  2017    12   Third   312
29556       58984     1       312         3       1  2017    12   First   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
9861       20  ...               63.0         9.0             6.0
9862       18  ...               63.0         9.0             6.0
9863        8  ...               63.0         9.0             6.0
9864        9  ...               63.0         9.0             6.0
9865       21  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
29552      45  ...               14.0         1.0             3.0
29553      35  ...               14.0         1.0             3.0
29554      29  ...               14.0         1.0             3.0
29555      42  ...               14.0         1.0             3.0
29556      22  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
9861                   1.0              92.0     169276.405792
9862                   1.0              92.0     169276.405792
9863                   1.0              92.0     169276.405792
9864                   1.0              92.0     169276.405792
9865                   1.0              92.0     169276.405792
...                    ...               ...               ...
29552                  1.0              38.0     200633.844449
29553                  1.0              38.0     200633.844449
29554                  1.0              38.0     200633.844449
29555                  1.0              38.0     200633.844449
29556                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
9861       13283.675264    5454.068890       3258.006066             0.167331
9862       13283.675264    5454.068890       3258.006066             0.167331
9863       13283.675264    5454.068890       3258.006066             0.167331
9864       13283.675264    5454.068890       3258.006066             0.167331
9865       13283.675264    5454.068890       3258.006066             0.167331
...                 ...            ...               ...                  ...
29552       4144.689546    4843.037238       4374.482421             0.135889
29553       4144.689546    4843.037238       4374.482421             0.139373
29554       4144.689546    4843.037238       4374.482421             0.139373
29555       4144.689546    4843.037238       4374.482421             0.139373
29556       4144.689546    4843.037238       4374.482421             0.139373

[19696 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
0               0     1      1713        17       1  2015     1   Third  1713
1               1     1      1713        17       1  2015     1  Second  1713
2               2     1      1713        17       1  2015     1   First  1713
3               3     1      1713        17       1  2015     2  Second  1713
4               4     1      1713        17       1  2015     2   Third  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
19707       58944     1       312         3       1  2016    11   First   312
19708       58945     1       312         3       1  2016    11  Second   312
19709       58946     1       312         3       1  2016    12   First   312
19710       58947     1       312         3       1  2016    12  Second   312
19711       58948     1       312         3       1  2016    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
0          16  ...               63.0         9.0             6.0
1          20  ...               63.0         9.0             6.0
2          14  ...               63.0         9.0             6.0
3          12  ...               63.0         9.0             6.0
4          12  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
19707      11  ...               14.0         1.0             3.0
19708      40  ...               14.0         1.0             3.0
19709      17  ...               14.0         1.0             3.0
19710      39  ...               14.0         1.0             3.0
19711      42  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
0                      1.0              92.0     169276.405792
1                      1.0              92.0     169276.405792
2                      1.0              92.0     169276.405792
3                      1.0              92.0     169276.405792
4                      1.0              92.0     169276.405792
...                    ...               ...               ...
19707                  1.0              38.0     200633.844449
19708                  1.0              38.0     200633.844449
19709                  1.0              38.0     200633.844449
19710                  1.0              38.0     200633.844449
19711                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
0          13283.675264    5454.068890       3258.006066             0.155378
1          13283.675264    5454.068890       3258.006066             0.155378
2          13283.675264    5454.068890       3258.006066             0.155378
3          13283.675264    5454.068890       3258.006066             0.155378
4          13283.675264    5454.068890       3258.006066             0.155378
...                 ...            ...               ...                  ...
19707       4144.689546    4843.037238       4374.482421             0.156794
19708       4144.689546    4843.037238       4374.482421             0.156794
19709       4144.689546    4843.037238       4374.482421             0.156794
19710       4144.689546    4843.037238       4374.482421             0.153310
19711       4144.689546    4843.037238       4374.482421             0.153310

[19712 rows x 31 columns]
Finished splitting...
Working on: [2017 2018]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.852368
1    0.852368
2    0.852368
3    0.852368
4    0.852368
Name: principal component 1, dtype: float64
(19695, 2) (19695, 328)
Working on: [2016 2017]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.85269
1    0.85269
2    0.85269
3    0.85269
4    0.85269
Name: principal component 1, dtype: float64
(19696, 2) (19696, 328)
Working on: [2015 2016]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...

<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

0    0.856576
1    0.856576
2    0.856576
3    0.856576
4    0.856576
Name: principal component 1, dtype: float64
(19712, 2) (19712, 328)
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
29557         108     1      1713        17       1  2018     1   First  1713
29558         109     1      1713        17       1  2018     1  Second  1713
29559         110     1      1713        17       1  2018     1   Third  1713
29560         111     1      1713        17       1  2018     2   Third  1713
29561         112     1      1713        17       1  2018     2   First  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
49256       59052     1       312         3       1  2019    11  Second   312
49257       59053     1       312         3       1  2019    11   Third   312
49258       59054     1       312         3       1  2019    12  Second   312
49259       59055     1       312         3       1  2019    12   First   312
49260       59056     1       312         3       1  2019    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
29557       8  ...               63.0         9.0             6.0
29558      16  ...               63.0         9.0             6.0
29559      24  ...               63.0         9.0             6.0
29560      16  ...               63.0         9.0             6.0
29561       8  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
49256      43  ...               14.0         1.0             3.0
49257      28  ...               14.0         1.0             3.0
49258      33  ...               14.0         1.0             3.0
49259      19  ...               14.0         1.0             3.0
49260      31  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
29557                  1.0              92.0     169276.405792
29558                  1.0              92.0     169276.405792
29559                  1.0              92.0     169276.405792
29560                  1.0              92.0     169276.405792
29561                  1.0              92.0     169276.405792
...                    ...               ...               ...
49256                  1.0              38.0     200633.844449
49257                  1.0              38.0     200633.844449
49258                  1.0              38.0     200633.844449
49259                  1.0              38.0     200633.844449
49260                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
29557      13283.675264    5454.068890       3258.006066             0.231076
29558      13283.675264    5454.068890       3258.006066             0.231076
29559      13283.675264    5454.068890       3258.006066             0.231076
29560      13283.675264    5454.068890       3258.006066             0.231076
29561      13283.675264    5454.068890       3258.006066             0.231076
...                 ...            ...               ...                  ...
49256       4144.689546    4843.037238       4374.482421             0.174216
49257       4144.689546    4843.037238       4374.482421             0.174216
49258       4144.689546    4843.037238       4374.482421             0.170732
49259       4144.689546    4843.037238       4374.482421             0.174216
49260       4144.689546    4843.037238       4374.482421             0.174216

[19704 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
19712          72     1      1713        17       1  2017     1   First  1713
19713          73     1      1713        17       1  2017     1   Third  1713
19714          74     1      1713        17       1  2017     1  Second  1713
19715          75     1      1713        17       1  2017     2  Second  1713
19716          76     1      1713        17       1  2017     2   Third  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
39402       59016     1       312         3       1  2018    11   Third   312
39403       59017     1       312         3       1  2018    11   First   312
39404       59018     1       312         3       1  2018    12   First   312
39405       59019     1       312         3       1  2018    12  Second   312
39406       59020     1       312         3       1  2018    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
19712      17  ...               63.0         9.0             6.0
19713      23  ...               63.0         9.0             6.0
19714      17  ...               63.0         9.0             6.0
19715      10  ...               63.0         9.0             6.0
19716      19  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
39402      33  ...               14.0         1.0             3.0
39403      12  ...               14.0         1.0             3.0
39404      15  ...               14.0         1.0             3.0
39405      36  ...               14.0         1.0             3.0
39406      34  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
19712                  1.0              92.0     169276.405792
19713                  1.0              92.0     169276.405792
19714                  1.0              92.0     169276.405792
19715                  1.0              92.0     169276.405792
19716                  1.0              92.0     169276.405792
...                    ...               ...               ...
39402                  1.0              38.0     200633.844449
39403                  1.0              38.0     200633.844449
39404                  1.0              38.0     200633.844449
39405                  1.0              38.0     200633.844449
39406                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
19712      13283.675264    5454.068890       3258.006066             0.243028
19713      13283.675264    5454.068890       3258.006066             0.243028
19714      13283.675264    5454.068890       3258.006066             0.243028
19715      13283.675264    5454.068890       3258.006066             0.243028
19716      13283.675264    5454.068890       3258.006066             0.243028
...                 ...            ...               ...                  ...
39402       4144.689546    4843.037238       4374.482421             0.104530
39403       4144.689546    4843.037238       4374.482421             0.104530
39404       4144.689546    4843.037238       4374.482421             0.104530
39405       4144.689546    4843.037238       4374.482421             0.101045
39406       4144.689546    4843.037238       4374.482421             0.104530

[19695 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
9861           36     1      1713        17       1  2016     1  Second  1713
9862           37     1      1713        17       1  2016     1   Third  1713
9863           38     1      1713        17       1  2016     1   First  1713
9864           39     1      1713        17       1  2016     2   First  1713
9865           40     1      1713        17       1  2016     2  Second  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
29552       58980     1       312         3       1  2017    11  Second   312
29553       58981     1       312         3       1  2017    11   Third   312
29554       58982     1       312         3       1  2017    12  Second   312
29555       58983     1       312         3       1  2017    12   Third   312
29556       58984     1       312         3       1  2017    12   First   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
9861       20  ...               63.0         9.0             6.0
9862       18  ...               63.0         9.0             6.0
9863        8  ...               63.0         9.0             6.0
9864        9  ...               63.0         9.0             6.0
9865       21  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
29552      45  ...               14.0         1.0             3.0
29553      35  ...               14.0         1.0             3.0
29554      29  ...               14.0         1.0             3.0
29555      42  ...               14.0         1.0             3.0
29556      22  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
9861                   1.0              92.0     169276.405792
9862                   1.0              92.0     169276.405792
9863                   1.0              92.0     169276.405792
9864                   1.0              92.0     169276.405792
9865                   1.0              92.0     169276.405792
...                    ...               ...               ...
29552                  1.0              38.0     200633.844449
29553                  1.0              38.0     200633.844449
29554                  1.0              38.0     200633.844449
29555                  1.0              38.0     200633.844449
29556                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
9861       13283.675264    5454.068890       3258.006066             0.167331
9862       13283.675264    5454.068890       3258.006066             0.167331
9863       13283.675264    5454.068890       3258.006066             0.167331
9864       13283.675264    5454.068890       3258.006066             0.167331
9865       13283.675264    5454.068890       3258.006066             0.167331
...                 ...            ...               ...                  ...
29552       4144.689546    4843.037238       4374.482421             0.135889
29553       4144.689546    4843.037238       4374.482421             0.139373
29554       4144.689546    4843.037238       4374.482421             0.139373
29555       4144.689546    4843.037238       4374.482421             0.139373
29556       4144.689546    4843.037238       4374.482421             0.139373

[19696 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
0               0     1      1713        17       1  2015     1   Third  1713
1               1     1      1713        17       1  2015     1  Second  1713
2               2     1      1713        17       1  2015     1   First  1713
3               3     1      1713        17       1  2015     2  Second  1713
4               4     1      1713        17       1  2015     2   Third  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
19707       58944     1       312         3       1  2016    11   First   312
19708       58945     1       312         3       1  2016    11  Second   312
19709       58946     1       312         3       1  2016    12   First   312
19710       58947     1       312         3       1  2016    12  Second   312
19711       58948     1       312         3       1  2016    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
0          16  ...               63.0         9.0             6.0
1          20  ...               63.0         9.0             6.0
2          14  ...               63.0         9.0             6.0
3          12  ...               63.0         9.0             6.0
4          12  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
19707      11  ...               14.0         1.0             3.0
19708      40  ...               14.0         1.0             3.0
19709      17  ...               14.0         1.0             3.0
19710      39  ...               14.0         1.0             3.0
19711      42  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
0                      1.0              92.0     169276.405792
1                      1.0              92.0     169276.405792
2                      1.0              92.0     169276.405792
3                      1.0              92.0     169276.405792
4                      1.0              92.0     169276.405792
...                    ...               ...               ...
19707                  1.0              38.0     200633.844449
19708                  1.0              38.0     200633.844449
19709                  1.0              38.0     200633.844449
19710                  1.0              38.0     200633.844449
19711                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
0          13283.675264    5454.068890       3258.006066             0.155378
1          13283.675264    5454.068890       3258.006066             0.155378
2          13283.675264    5454.068890       3258.006066             0.155378
3          13283.675264    5454.068890       3258.006066             0.155378
4          13283.675264    5454.068890       3258.006066             0.155378
...                 ...            ...               ...                  ...
19707       4144.689546    4843.037238       4374.482421             0.156794
19708       4144.689546    4843.037238       4374.482421             0.156794
19709       4144.689546    4843.037238       4374.482421             0.156794
19710       4144.689546    4843.037238       4374.482421             0.153310
19711       4144.689546    4843.037238       4374.482421             0.153310

[19712 rows x 31 columns]
Finished splitting...
Working on: [2017 2018]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.852368
1    0.852368
2    0.852368
3    0.852368
4    0.852368
Name: principal component 1, dtype: float64
(19695, 2) (19695, 328)
Working on: [2016 2017]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.85269
1    0.85269
2    0.85269
3    0.85269
4    0.85269
Name: principal component 1, dtype: float64
(19696, 2) (19696, 328)
Working on: [2015 2016]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.856576
1    0.856576
2    0.856576
3    0.856576
4    0.856576
Name: principal component 1, dtype: float64
(19712, 2) (19712, 328)
         Unnamed: 0  Beat  Year  Month   Watch  PRCP  SNOW  TMAX  TMIN  \
1240034     1240034  1433  2019      8   Third  0.00   0.0    78    69
1155931     1155931  1221  2019      5   First  0.45   0.0    76    47
1087011     1087011  1832  2019      1  Second  0.00   0.1    23     3
1177045     1177045   114  2019      6   Third  0.12   0.0    83    60
1214968     1214968   523  2019      7  Second  0.00   0.0    76    63
...             ...   ...   ...    ...     ...   ...   ...   ...   ...
1218365     1218365   734  2019      7   Third  0.00   0.0    86    68
1157148     1157148   424  2019      5   Third  1.21   0.0    69    49
1236720     1236720  2514  2019      8  Second  1.24   0.0    84    69
1093551     1093551  1234  2019      2   Third  0.03   0.0    51    30
1259264     1259264   223  2019      9  Second  0.00   0.0    79    66

         count_l_stops  ...  count_restaurants  count_bars  count_daycares  \
1240034            0.0  ...               66.0        36.0             3.0
1155931            0.0  ...               43.0        19.0             6.0
1087011            0.0  ...               91.0        69.0             3.0
1177045            0.0  ...              116.0        47.0             3.0
1214968            0.0  ...                7.0         3.0             1.0
...                ...  ...                ...         ...             ...
1218365            0.0  ...                7.0         2.0             1.0
1157148            0.0  ...               24.0         3.0             6.0
1236720            0.0  ...               89.0        18.0            10.0
1093551            3.0  ...               70.0         7.0             4.0
1259264            0.0  ...               21.0         3.0             0.0

         count_entertainment  count_businesses  road_distance_ft  \
1240034                 11.0             178.0          0.651032
1155931                  0.0             227.0          1.120417
1087011                 20.0             166.0          0.268514
1177045                  7.0             368.0          1.089054
1214968                  0.0              24.0          0.819340
...                      ...               ...               ...
1218365                  1.0              21.0          0.463460
1157148                  0.0              56.0          0.908809
1236720                  4.0             156.0          0.761091
1093551                  0.0             108.0          0.471905
1259264                  1.0              30.0          0.424687

         TOTAL POPULATION  dist_to_police  dist_to_hospital  was_arrested
1240034       8171.172717        0.022891          0.019866           0.0
1155931       8577.875630        0.024901          0.011968           0.0
1087011       8038.135255        0.014020          0.009861           0.0
1177045       9743.301103        0.022256          0.015583           0.0
1214968      11441.294492        0.039643          0.027001           0.0
...                   ...             ...               ...           ...
1218365       4391.423523        0.016567          0.030056           0.0
1157148       7656.137685        0.039379          0.026725           1.0
1236720      17463.094185        0.015317          0.012465           0.0
1093551      14882.673469        0.019607          0.014222           0.0
1259264       7269.595565        0.020448          0.004761           0.0

[275 rows x 22 columns]
         Unnamed: 0  Beat  Year  Month   Watch  PRCP  SNOW  TMAX  TMIN  \
961499       961499   114  2018      8   Third  0.01   0.0    95    76
993733       993733   735  2018      9  Second  0.00   0.0    83    63
804936       804936   332  2018      1  Second  0.00   0.0    13     2
1032965     1032965   421  2018     11   Third  0.05   0.0    50    38
994609       994609   622  2018      9   Third  0.00   0.0    89    67
...             ...   ...   ...    ...     ...   ...   ...   ...   ...
842561       842561  2525  2018      3   Third  0.00   0.0    43    35
1017816     1017816  1024  2018     10   Third  0.00   0.0    52    39
980933       980933   912  2018      8   First  0.00   0.0    74    64
1058957     1058957  1834  2018     12  Second  0.16   0.0    42    35
934505       934505  1021  2018      7   Third  0.00   0.0    91    68

         count_l_stops  ...  count_restaurants  count_bars  count_daycares  \
961499             0.0  ...              116.0        47.0             3.0
993733             0.0  ...               14.0         0.0             2.0
804936             0.0  ...               15.0         2.0             3.0
1032965            0.0  ...                7.0         1.0             3.0
994609             0.0  ...               25.0         2.0             0.0
...                ...  ...                ...         ...             ...
842561             0.0  ...               29.0         8.0             2.0
1017816            1.0  ...               32.0         3.0             0.0
980933             1.0  ...               52.0         6.0             7.0
1058957            1.0  ...              332.0       238.0             7.0
934505             0.0  ...                5.0         0.0             1.0

         count_entertainment  count_businesses  road_distance_ft  \
961499                   7.0             368.0          1.089054
993733                   0.0              26.0          0.611139
804936                   1.0              45.0          0.400015
1032965                  0.0              37.0          0.499217
994609                   1.0              56.0          0.707590
...                      ...               ...               ...
842561                   3.0              85.0          0.474694
1017816                  1.0              86.0          0.466057
980933                   0.0             151.0          1.343846
1058957                 49.0             676.0          0.909764
934505                   0.0               6.0          0.383696

         TOTAL POPULATION  dist_to_police  dist_to_hospital  was_arrested
961499        9743.301103        0.022256          0.015583           0.0
993733        5921.754724        0.020226          0.022043           1.0
804936        6647.401609        0.022760          0.012327           0.0
1032965      10253.749063        0.050269          0.015925           1.0
994609        2863.111097        0.014556          0.036939           1.0
...                   ...             ...               ...           ...
842561       10593.560235        0.026441          0.019964           0.0
1017816      11569.102587        0.006914          0.013311           0.0
980933       14747.874880        0.025219          0.035682           0.0
1058957      16374.716120        0.029290          0.003678           1.0
934505        5045.433242        0.005713          0.014386           1.0

[261 rows x 22 columns]
        Unnamed: 0  Beat  Year  Month   Watch  PRCP  SNOW  TMAX  TMIN  \
775278      775278  1233  2017     11   Third  0.06   0.0    45    28
800987      800987   725  2017     12   Third  0.03   0.7    14     2
717369      717369   612  2017      9   Third  0.00   0.0    84    65
583297      583297   824  2017      3   Third  0.01   0.1    36    20
709307      709307   814  2017      8   First  0.00   0.0    73    53
...            ...   ...   ...    ...     ...   ...   ...   ...   ...
741095      741095  2023  2017     10   Third  0.04   0.0    76    56
720824      720824  1613  2017      9   Third  0.00   0.0    71    57
737697      737697   331  2017     10  Second  0.00   0.0    72    52
547475      547475  1533  2017      1  Second  0.21   0.0    47    37
719248      719248   813  2017      9  Second  0.00   0.0    70    53

        count_l_stops  ...  count_restaurants  count_bars  count_daycares  \
775278            0.0  ...               61.0        13.0             5.0
800987            1.0  ...               13.0         0.0             2.0
717369            0.0  ...               12.0         1.0             6.0
583297            0.0  ...               49.0         3.0             7.0
709307            0.0  ...               30.0        10.0             1.0
...               ...  ...                ...         ...             ...
741095            2.0  ...               35.0         9.0             2.0
720824            0.0  ...               30.0        10.0             3.0
737697            0.0  ...               20.0         8.0             1.0
547475            1.0  ...               21.0         3.0             1.0
719248            1.0  ...              138.0        45.0             5.0

        count_entertainment  count_businesses  road_distance_ft  \
775278                  2.0             125.0          0.969649
800987                  0.0              24.0          0.457074
717369                  0.0              35.0          0.622271
583297                  0.0             126.0          0.836459
709307                  2.0              64.0          0.791764
...                     ...               ...               ...
741095                  1.0              51.0          0.275006
720824                  1.0              93.0          1.280451
737697                  2.0              46.0          1.064898
547475                  0.0              53.0          0.449942
719248                  1.0             207.0          1.551454

        TOTAL POPULATION  dist_to_police  dist_to_hospital  was_arrested
775278       6373.273003        0.013074          0.007271           0.0
800987       5168.646461        0.007154          0.028739           0.0
717369       9622.912845        0.011763          0.034967           0.0
583297      15413.588923        0.019887          0.020102           0.0
709307       9690.564218        0.047393          0.066600           0.0
...                  ...             ...               ...           ...
741095       9608.317084        0.026003          0.010589           0.0
720824      14274.021602        0.038312          0.014228           0.0
737697       8902.799662        0.030812          0.006801           0.0
547475       7038.112338        0.019818          0.013749           0.0
719248      21819.823082        0.033934          0.052171           0.0

[276 rows x 22 columns]
        Unnamed: 0  Beat  Year  Month   Watch  PRCP  SNOW  TMAX  TMIN  \
286086      286086  1812  2016      2   First  0.78   0.0    40    36
387019      387019  1121  2016      6  Second  0.00   0.0    85    66
335709      335709   923  2016      4   First  0.00   0.0    69    45
388872      388872  2412  2016      6   Third  0.00   0.0    80    67
376608      376608  1122  2016      6  Second  0.00   0.0    70    54
...            ...   ...   ...    ...     ...   ...   ...   ...   ...
314834      314834   112  2016      3  Second  0.12   0.0    58    47
413352      413352   113  2016      7  Second  0.70   0.0    94    73
527525      527525  1523  2016     12  Second  0.00   0.0    39    27
530387      530387  2514  2016     12   Third  0.26   0.0    55    30
308076      308076  1434  2016      3   Third  0.00   0.0    53    35

        count_l_stops  ...  count_restaurants  count_bars  count_daycares  \
286086            2.0  ...              119.0        48.0             5.0
387019            0.0  ...               25.0         0.0             1.0
335709            0.0  ...               52.0         5.0             2.0
388872            0.0  ...               93.0         5.0             5.0
376608            1.0  ...               19.0         0.0             0.0
...               ...  ...                ...         ...             ...
314834            4.0  ...              130.0        55.0             1.0
413352            4.0  ...               91.0        23.0             1.0
527525            0.0  ...               11.0         0.0             0.0
530387            0.0  ...               89.0        18.0            10.0
308076            1.0  ...               90.0        41.0            13.0

        count_entertainment  count_businesses  road_distance_ft  \
286086                 13.0             126.0          0.418606
387019                  0.0              56.0          0.597790
335709                  2.0              74.0          0.700729
388872                  2.0             165.0          0.756025
376608                  1.0              66.0          0.685754
...                     ...               ...               ...
314834                 15.0             669.0          0.161066
413352                  8.0             212.0          0.150686
527525                  0.0              18.0          0.393697
530387                  4.0             156.0          0.761091
308076                  6.0             202.0          0.622163

        TOTAL POPULATION  dist_to_police  dist_to_hospital  was_arrested
286086       8365.503423        0.018854          0.003387           1.0
387019       7026.957744        0.023843          0.006807           0.0
335709      15377.239925        0.025119          0.029941           0.0
388872      17772.958410        0.021143          0.026463           0.0
376608       5159.409728        0.019547          0.005248           0.0
...                  ...             ...               ...           ...
314834       1195.459578        0.022807          0.014610           0.0
413352       1746.267459        0.019029          0.018079           0.0
527525       6376.246288        0.010972          0.014966           1.0
530387      17463.094185        0.015317          0.012465           1.0
308076      11020.867583        0.016993          0.007159           0.0

[236 rows x 22 columns]
        Unnamed: 0  Beat  Year  Month  Watch  PRCP  SNOW  TMAX  TMIN  \
164846      164846   312  2015      8  First  0.15   0.0    90    72
66064        66064   513  2015      4  Third  0.00   0.0    65    42
125233      125233  1924  2015      6  Third  0.00   0.0    77    59
39914        39914  1523  2015      3  Third  0.00   0.0    33    14
101474      101474   725  2015      5  First  0.00   0.0    84    60
...            ...   ...   ...    ...    ...   ...   ...   ...   ...
29075        29075  2013  2015      2  Third  0.00   0.2    29     4
174017      174017  1113  2015      8  Third  0.00   0.0    76    62
80040        80040   733  2015      4  Third  0.00   0.0    64    42
122394      122394  2212  2015      6  First  0.00   0.0    79    66
78572        78572  1122  2015      4  First  0.00   0.0    60    38

        count_l_stops  ...  count_restaurants  count_bars  count_daycares  \
164846            2.0  ...               14.0         1.0             3.0
66064             0.0  ...               14.0         0.0             2.0
125233            1.0  ...              128.0        90.0             8.0
39914             0.0  ...               11.0         0.0             0.0
101474            1.0  ...               13.0         0.0             2.0
...               ...  ...                ...         ...             ...
29075             0.0  ...               59.0        26.0             3.0
174017            1.0  ...               12.0         1.0             2.0
80040             0.0  ...               11.0         1.0             1.0
122394            0.0  ...               40.0         8.0            10.0
78572             1.0  ...               19.0         0.0             0.0

        count_entertainment  count_businesses  road_distance_ft  \
164846                  1.0              38.0          0.674669
66064                   0.0              45.0          0.850162
125233                 37.0             115.0          0.441366
39914                   0.0              18.0          0.393697
101474                  0.0              24.0          0.457074
...                     ...               ...               ...
29075                   4.0             119.0          0.546648
174017                  1.0              44.0          0.465835
80040                   0.0              15.0          0.446254
122394                  0.0             155.0          1.627776
78572                   1.0              66.0          0.685754

        TOTAL POPULATION  dist_to_police  dist_to_hospital  was_arrested
164846       4144.689634        0.015081          0.016011           0.0
66064        7489.527304        0.011224          0.011974           1.0
125233      11323.989570        0.006767          0.008535           0.0
39914        6376.246288        0.010972          0.014966           1.0
101474       5168.646461        0.007154          0.028739           0.0
...                  ...             ...               ...           ...
29075       10850.790931        0.017459          0.012659           0.0
174017       4161.746005        0.028441          0.021861           1.0
80040        4906.580008        0.012347          0.022164           1.0
122394      18875.580749        0.007211          0.051043           0.0
78572        5159.409728        0.019547          0.005248           0.0

[296 rows x 22 columns]
Finished splitting...
Working on: [2018]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
Working on: [2017]
Have accessed train and test df...

Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
Working on: [2016]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
Working on: [2015]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...

In [2]:
import pandas as pd
import geopandas as gpd
import seaborn as sns
import numpy as np
import sklearn as sk
from sklearn import preprocessing
from sklearn.pipeline import Pipeline
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score
import datetime

#### Read and Process Data

In [3]:
data = pd.read_csv("../intermediate_data/high_crime_labeled.csv")
data = data.drop(columns=["beat", "beat_num", "Crimes", "Arrest"])
data = convert_to_categorical(data, ["district", "sector",
                                    "Month",
                                     "Watch", "Beat"])
data.drop(columns = ["Unnamed: 0"], inplace=True)

#### Setup ML

In [4]:
models = {
    'DecisionTreeClassifier': DecisionTreeClassifier(), 
}
grid = {
    'DecisionTreeClassifier': [{'criterion': x, 'max_depth': y, 'min_samples_split':z, 'random_state': 0} 
                           for x in ('gini', 'entropy') \
                           for y in (1, 3, 5, 10, 15, 20, 30) \
                           for z in (2, 4, 6, 8, 10, 12, 13, 14, 15)
                              ]
}

In [5]:
data_list = prep_data(data, "high_crime",
                                        2, "Year", ["district", "sector", 
                                                    "Month", 
                                                    "Beat", "Watch"])

data_list_pca = prep_data(data, "high_crime",
                                        2, "Year", 
                          ["district", "sector", 
                                                    "Month", 
                                                    "Beat", "Watch"], pca="yes!", 
                                                  columns_to_pca = ["TOTAL POPULATION", "dist_to_police",
                                                                   "dist_to_hospital", 
                                                  "count_l_stops", "count_bus_stops", 
                                               "count_metra_stops", "count_restaurants", "count_bars", 
                                               "count_daycares", "count_entertainment", "count_businesses", 
                                               "road_distance_ft"])

      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
29557       17      1  2018     1   First  1713      1.0         2  33.201426
29558       17      1  2018     1  Second  1713      8.0         4  33.201426
29559       17      1  2018     1   Third  1713     11.0         4  33.201426
29560       17      1  2018     2   Third  1713      5.0         3  39.791635
29561       17      1  2018     2   First  1713      6.0         2  39.791635
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
49256        3      1  2019    11  Second   312     13.0        11  43.761013
49257        3      1  2019    11   Third   312     13.0         8  43.761013
49258        3      1  2019    12  Second   312     20.0         8  42.647269
49259        3      1  2019    12   First   312      7.0         8  42.647269
49260        3      1  2019    12   Third   312     13.0         4  42.647269

            TMIN  ...  count_restaurants  count_bars count_daycares  \
29557  18.884223  ...               63.0         9.0            6.0
29558  18.884223  ...               63.0         9.0            6.0
29559  18.884223  ...               63.0         9.0            6.0
29560  22.439919  ...               63.0         9.0            6.0
29561  22.439919  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
49256  29.648049  ...               14.0         1.0            3.0
49257  29.648049  ...               14.0         1.0            3.0
49258  27.854899  ...               14.0         1.0            3.0
49259  27.854899  ...               14.0         1.0            3.0
49260  27.854899  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
29557                  1.0              92.0     169276.405792
29558                  1.0              92.0     169276.405792
29559                  1.0              92.0     169276.405792
29560                  1.0              92.0     169276.405792
29561                  1.0              92.0     169276.405792
...                    ...               ...               ...
49256                  1.0              38.0     200633.844449
49257                  1.0              38.0     200633.844449
49258                  1.0              38.0     200633.844449
49259                  1.0              38.0     200633.844449
49260                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
29557      13283.675264     5454.068890       3258.006066             0.231076
29558      13283.675264     5454.068890       3258.006066             0.231076
29559      13283.675264     5454.068890       3258.006066             0.231076
29560      13283.675264     5454.068890       3258.006066             0.231076
29561      13283.675264     5454.068890       3258.006066             0.231076
...                 ...             ...               ...                  ...
49256       4144.689546     4843.037238       4374.482421             0.174216
49257       4144.689546     4843.037238       4374.482421             0.174216
49258       4144.689546     4843.037238       4374.482421             0.170732
49259       4144.689546     4843.037238       4374.482421             0.174216
49260       4144.689546     4843.037238       4374.482421             0.174216

[19704 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
19712       17      1  2017     1   First  1713      6.0         5  36.668219
19713       17      1  2017     1   Third  1713     16.0         4  36.668219
19714       17      1  2017     1  Second  1713     13.0         2  36.668219
19715       17      1  2017     2  Second  1713      7.0         2  48.828937
19716       17      1  2017     2   Third  1713      9.0         3  48.828937
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
39402        3      1  2018    11   Third   312     15.0         7  40.859811
39403        3      1  2018    11   First   312      7.0         4  40.859811
39404        3      1  2018    12   First   312      7.0         4  40.587445
39405        3      1  2018    12  Second   312     20.0        12  40.587445
39406        3      1  2018    12   Third   312     14.0         7  40.587445

            TMIN  ...  count_restaurants  count_bars count_daycares  \
19712  25.445660  ...               63.0         9.0            6.0
19713  25.445660  ...               63.0         9.0            6.0
19714  25.445660  ...               63.0         9.0            6.0
19715  30.957247  ...               63.0         9.0            6.0
19716  30.957247  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
39402  30.481732  ...               14.0         1.0            3.0
39403  30.481732  ...               14.0         1.0            3.0
39404  27.929352  ...               14.0         1.0            3.0
39405  27.929352  ...               14.0         1.0            3.0
39406  27.929352  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
19712                  1.0              92.0     169276.405792
19713                  1.0              92.0     169276.405792
19714                  1.0              92.0     169276.405792
19715                  1.0              92.0     169276.405792
19716                  1.0              92.0     169276.405792
...                    ...               ...               ...
39402                  1.0              38.0     200633.844449
39403                  1.0              38.0     200633.844449
39404                  1.0              38.0     200633.844449
39405                  1.0              38.0     200633.844449
39406                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
19712      13283.675264     5454.068890       3258.006066             0.243028
19713      13283.675264     5454.068890       3258.006066             0.243028
19714      13283.675264     5454.068890       3258.006066             0.243028
19715      13283.675264     5454.068890       3258.006066             0.243028
19716      13283.675264     5454.068890       3258.006066             0.243028
...                 ...             ...               ...                  ...
39402       4144.689546     4843.037238       4374.482421             0.104530
39403       4144.689546     4843.037238       4374.482421             0.104530
39404       4144.689546     4843.037238       4374.482421             0.104530
39405       4144.689546     4843.037238       4374.482421             0.101045
39406       4144.689546     4843.037238       4374.482421             0.104530

[19695 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
9861        17      1  2016     1  Second  1713     10.0         3  34.634797
9862        17      1  2016     1   Third  1713     11.0         4  34.634797
9863        17      1  2016     1   First  1713      2.0         4  34.634797
9864        17      1  2016     2   First  1713      5.0         0  39.873946
9865        17      1  2016     2  Second  1713     14.0         2  39.873946
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
29552        3      1  2017    11  Second   312     21.0        10  48.004051
29553        3      1  2017    11   Third   312     15.0         8  48.004051
29554        3      1  2017    12  Second   312      7.0         7  36.924981
29555        3      1  2017    12   Third   312     16.0        14  36.924981
29556        3      1  2017    12   First   312     11.0        11  36.924981

            TMIN  ...  count_restaurants  count_bars count_daycares  \
9861   21.333060  ...               63.0         9.0            6.0
9862   21.333060  ...               63.0         9.0            6.0
9863   21.333060  ...               63.0         9.0            6.0
9864   26.515109  ...               63.0         9.0            6.0
9865   26.515109  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
29552  33.954321  ...               14.0         1.0            3.0
29553  33.954321  ...               14.0         1.0            3.0
29554  23.299649  ...               14.0         1.0            3.0
29555  23.299649  ...               14.0         1.0            3.0
29556  23.299649  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
9861                   1.0              92.0     169276.405792
9862                   1.0              92.0     169276.405792
9863                   1.0              92.0     169276.405792
9864                   1.0              92.0     169276.405792
9865                   1.0              92.0     169276.405792
...                    ...               ...               ...
29552                  1.0              38.0     200633.844449
29553                  1.0              38.0     200633.844449
29554                  1.0              38.0     200633.844449
29555                  1.0              38.0     200633.844449
29556                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
9861       13283.675264     5454.068890       3258.006066             0.167331
9862       13283.675264     5454.068890       3258.006066             0.167331
9863       13283.675264     5454.068890       3258.006066             0.167331
9864       13283.675264     5454.068890       3258.006066             0.167331
9865       13283.675264     5454.068890       3258.006066             0.167331
...                 ...             ...               ...                  ...
29552       4144.689546     4843.037238       4374.482421             0.135889
29553       4144.689546     4843.037238       4374.482421             0.139373
29554       4144.689546     4843.037238       4374.482421             0.139373
29555       4144.689546     4843.037238       4374.482421             0.139373
29556       4144.689546     4843.037238       4374.482421             0.139373

[19696 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
0           17      1  2015     1   Third  1713     10.0         1  32.469987
1           17      1  2015     1  Second  1713     13.0         4  32.469987
2           17      1  2015     1   First  1713      5.0         3  32.469987
3           17      1  2015     2  Second  1713      7.0         1  26.455588
4           17      1  2015     2   Third  1713      5.0         3  26.455588
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
19707        3      1  2016    11   First   312      7.0         4  56.907539
19708        3      1  2016    11  Second   312     20.0         8  56.907539
19709        3      1  2016    12   First   312      8.0         4  33.189478
19710        3      1  2016    12  Second   312     20.0         8  33.189478
19711        3      1  2016    12   Third   312     21.0         4  33.189478

            TMIN  ...  count_restaurants  count_bars count_daycares  \
0      20.138549  ...               63.0         9.0            6.0
1      20.138549  ...               63.0         9.0            6.0
2      20.138549  ...               63.0         9.0            6.0
3      10.647633  ...               63.0         9.0            6.0
4      10.647633  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
19707  41.575555  ...               14.0         1.0            3.0
19708  41.575555  ...               14.0         1.0            3.0
19709  22.018894  ...               14.0         1.0            3.0
19710  22.018894  ...               14.0         1.0            3.0
19711  22.018894  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
0                      1.0              92.0     169276.405792
1                      1.0              92.0     169276.405792
2                      1.0              92.0     169276.405792
3                      1.0              92.0     169276.405792
4                      1.0              92.0     169276.405792
...                    ...               ...               ...
19707                  1.0              38.0     200633.844449
19708                  1.0              38.0     200633.844449
19709                  1.0              38.0     200633.844449
19710                  1.0              38.0     200633.844449
19711                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
0          13283.675264     5454.068890       3258.006066             0.155378
1          13283.675264     5454.068890       3258.006066             0.155378
2          13283.675264     5454.068890       3258.006066             0.155378
3          13283.675264     5454.068890       3258.006066             0.155378
4          13283.675264     5454.068890       3258.006066             0.155378
...                 ...             ...               ...                  ...
19707       4144.689546     4843.037238       4374.482421             0.156794
19708       4144.689546     4843.037238       4374.482421             0.156794
19709       4144.689546     4843.037238       4374.482421             0.156794
19710       4144.689546     4843.037238       4374.482421             0.153310
19711       4144.689546     4843.037238       4374.482421             0.153310

[19712 rows x 26 columns]
Finished splitting...
Working on: [2017 2018]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...

Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
Working on: [2016 2017]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
Working on: [2015 2016]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
29557       17      1  2018     1   First  1713      1.0         2  33.201426
29558       17      1  2018     1  Second  1713      8.0         4  33.201426
29559       17      1  2018     1   Third  1713     11.0         4  33.201426
29560       17      1  2018     2   Third  1713      5.0         3  39.791635
29561       17      1  2018     2   First  1713      6.0         2  39.791635
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
49256        3      1  2019    11  Second   312     13.0        11  43.761013
49257        3      1  2019    11   Third   312     13.0         8  43.761013
49258        3      1  2019    12  Second   312     20.0         8  42.647269
49259        3      1  2019    12   First   312      7.0         8  42.647269
49260        3      1  2019    12   Third   312     13.0         4  42.647269

            TMIN  ...  count_restaurants  count_bars count_daycares  \
29557  18.884223  ...               63.0         9.0            6.0
29558  18.884223  ...               63.0         9.0            6.0
29559  18.884223  ...               63.0         9.0            6.0
29560  22.439919  ...               63.0         9.0            6.0
29561  22.439919  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
49256  29.648049  ...               14.0         1.0            3.0
49257  29.648049  ...               14.0         1.0            3.0
49258  27.854899  ...               14.0         1.0            3.0
49259  27.854899  ...               14.0         1.0            3.0
49260  27.854899  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
29557                  1.0              92.0     169276.405792
29558                  1.0              92.0     169276.405792
29559                  1.0              92.0     169276.405792
29560                  1.0              92.0     169276.405792
29561                  1.0              92.0     169276.405792
...                    ...               ...               ...
49256                  1.0              38.0     200633.844449
49257                  1.0              38.0     200633.844449
49258                  1.0              38.0     200633.844449
49259                  1.0              38.0     200633.844449
49260                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
29557      13283.675264     5454.068890       3258.006066             0.231076
29558      13283.675264     5454.068890       3258.006066             0.231076
29559      13283.675264     5454.068890       3258.006066             0.231076
29560      13283.675264     5454.068890       3258.006066             0.231076
29561      13283.675264     5454.068890       3258.006066             0.231076
...                 ...             ...               ...                  ...
49256       4144.689546     4843.037238       4374.482421             0.174216
49257       4144.689546     4843.037238       4374.482421             0.174216
49258       4144.689546     4843.037238       4374.482421             0.170732
49259       4144.689546     4843.037238       4374.482421             0.174216
49260       4144.689546     4843.037238       4374.482421             0.174216

[19704 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
19712       17      1  2017     1   First  1713      6.0         5  36.668219
19713       17      1  2017     1   Third  1713     16.0         4  36.668219
19714       17      1  2017     1  Second  1713     13.0         2  36.668219
19715       17      1  2017     2  Second  1713      7.0         2  48.828937
19716       17      1  2017     2   Third  1713      9.0         3  48.828937
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
39402        3      1  2018    11   Third   312     15.0         7  40.859811
39403        3      1  2018    11   First   312      7.0         4  40.859811
39404        3      1  2018    12   First   312      7.0         4  40.587445
39405        3      1  2018    12  Second   312     20.0        12  40.587445
39406        3      1  2018    12   Third   312     14.0         7  40.587445

            TMIN  ...  count_restaurants  count_bars count_daycares  \
19712  25.445660  ...               63.0         9.0            6.0
19713  25.445660  ...               63.0         9.0            6.0
19714  25.445660  ...               63.0         9.0            6.0
19715  30.957247  ...               63.0         9.0            6.0
19716  30.957247  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
39402  30.481732  ...               14.0         1.0            3.0
39403  30.481732  ...               14.0         1.0            3.0
39404  27.929352  ...               14.0         1.0            3.0
39405  27.929352  ...               14.0         1.0            3.0
39406  27.929352  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
19712                  1.0              92.0     169276.405792
19713                  1.0              92.0     169276.405792
19714                  1.0              92.0     169276.405792
19715                  1.0              92.0     169276.405792
19716                  1.0              92.0     169276.405792
...                    ...               ...               ...
39402                  1.0              38.0     200633.844449
39403                  1.0              38.0     200633.844449
39404                  1.0              38.0     200633.844449
39405                  1.0              38.0     200633.844449
39406                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
19712      13283.675264     5454.068890       3258.006066             0.243028
19713      13283.675264     5454.068890       3258.006066             0.243028
19714      13283.675264     5454.068890       3258.006066             0.243028
19715      13283.675264     5454.068890       3258.006066             0.243028
19716      13283.675264     5454.068890       3258.006066             0.243028
...                 ...             ...               ...                  ...
39402       4144.689546     4843.037238       4374.482421             0.104530
39403       4144.689546     4843.037238       4374.482421             0.104530
39404       4144.689546     4843.037238       4374.482421             0.104530
39405       4144.689546     4843.037238       4374.482421             0.101045
39406       4144.689546     4843.037238       4374.482421             0.104530

[19695 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
9861        17      1  2016     1  Second  1713     10.0         3  34.634797
9862        17      1  2016     1   Third  1713     11.0         4  34.634797
9863        17      1  2016     1   First  1713      2.0         4  34.634797
9864        17      1  2016     2   First  1713      5.0         0  39.873946
9865        17      1  2016     2  Second  1713     14.0         2  39.873946
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
29552        3      1  2017    11  Second   312     21.0        10  48.004051
29553        3      1  2017    11   Third   312     15.0         8  48.004051
29554        3      1  2017    12  Second   312      7.0         7  36.924981
29555        3      1  2017    12   Third   312     16.0        14  36.924981
29556        3      1  2017    12   First   312     11.0        11  36.924981

            TMIN  ...  count_restaurants  count_bars count_daycares  \
9861   21.333060  ...               63.0         9.0            6.0
9862   21.333060  ...               63.0         9.0            6.0
9863   21.333060  ...               63.0         9.0            6.0
9864   26.515109  ...               63.0         9.0            6.0
9865   26.515109  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
29552  33.954321  ...               14.0         1.0            3.0
29553  33.954321  ...               14.0         1.0            3.0
29554  23.299649  ...               14.0         1.0            3.0
29555  23.299649  ...               14.0         1.0            3.0
29556  23.299649  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
9861                   1.0              92.0     169276.405792
9862                   1.0              92.0     169276.405792
9863                   1.0              92.0     169276.405792
9864                   1.0              92.0     169276.405792
9865                   1.0              92.0     169276.405792
...                    ...               ...               ...
29552                  1.0              38.0     200633.844449
29553                  1.0              38.0     200633.844449
29554                  1.0              38.0     200633.844449
29555                  1.0              38.0     200633.844449
29556                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
9861       13283.675264     5454.068890       3258.006066             0.167331
9862       13283.675264     5454.068890       3258.006066             0.167331
9863       13283.675264     5454.068890       3258.006066             0.167331
9864       13283.675264     5454.068890       3258.006066             0.167331
9865       13283.675264     5454.068890       3258.006066             0.167331
...                 ...             ...               ...                  ...
29552       4144.689546     4843.037238       4374.482421             0.135889
29553       4144.689546     4843.037238       4374.482421             0.139373
29554       4144.689546     4843.037238       4374.482421             0.139373
29555       4144.689546     4843.037238       4374.482421             0.139373
29556       4144.689546     4843.037238       4374.482421             0.139373

[19696 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
0           17      1  2015     1   Third  1713     10.0         1  32.469987
1           17      1  2015     1  Second  1713     13.0         4  32.469987
2           17      1  2015     1   First  1713      5.0         3  32.469987
3           17      1  2015     2  Second  1713      7.0         1  26.455588
4           17      1  2015     2   Third  1713      5.0         3  26.455588
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
19707        3      1  2016    11   First   312      7.0         4  56.907539
19708        3      1  2016    11  Second   312     20.0         8  56.907539
19709        3      1  2016    12   First   312      8.0         4  33.189478
19710        3      1  2016    12  Second   312     20.0         8  33.189478
19711        3      1  2016    12   Third   312     21.0         4  33.189478

            TMIN  ...  count_restaurants  count_bars count_daycares  \
0      20.138549  ...               63.0         9.0            6.0
1      20.138549  ...               63.0         9.0            6.0
2      20.138549  ...               63.0         9.0            6.0
3      10.647633  ...               63.0         9.0            6.0
4      10.647633  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
19707  41.575555  ...               14.0         1.0            3.0
19708  41.575555  ...               14.0         1.0            3.0
19709  22.018894  ...               14.0         1.0            3.0
19710  22.018894  ...               14.0         1.0            3.0
19711  22.018894  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
0                      1.0              92.0     169276.405792
1                      1.0              92.0     169276.405792
2                      1.0              92.0     169276.405792
3                      1.0              92.0     169276.405792
4                      1.0              92.0     169276.405792
...                    ...               ...               ...
19707                  1.0              38.0     200633.844449
19708                  1.0              38.0     200633.844449
19709                  1.0              38.0     200633.844449
19710                  1.0              38.0     200633.844449
19711                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
0          13283.675264     5454.068890       3258.006066             0.155378
1          13283.675264     5454.068890       3258.006066             0.155378
2          13283.675264     5454.068890       3258.006066             0.155378
3          13283.675264     5454.068890       3258.006066             0.155378
4          13283.675264     5454.068890       3258.006066             0.155378
...                 ...             ...               ...                  ...
19707       4144.689546     4843.037238       4374.482421             0.156794
19708       4144.689546     4843.037238       4374.482421             0.156794
19709       4144.689546     4843.037238       4374.482421             0.156794
19710       4144.689546     4843.037238       4374.482421             0.153310
19711       4144.689546     4843.037238       4374.482421             0.153310

[19712 rows x 26 columns]
Finished splitting...
Working on: [2017 2018]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data

Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.852368
1    0.852368
2    0.852368
3    0.852368
4    0.852368
Name: principal component 1, dtype: float64
(19695, 2) (19695, 324)
Working on: [2016 2017]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.85269
1    0.85269
2    0.85269
3    0.85269
4    0.85269
Name: principal component 1, dtype: float64
(19696, 2) (19696, 324)
Working on: [2015 2016]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.856576
1    0.856576
2    0.856576
3    0.856576
4    0.856576
Name: principal component 1, dtype: float64
(19712, 2) (19712, 324)

In [6]:
tree_results = average_grid_searches(DecisionTreeClassifier(), "DecisionTreeClassifier", 
                          grid, 
                          data_list, "high_crime", 2020)

test year is: 2020
[2016, 2017, 2018, 2019]

In [7]:
tree_results_pca = average_grid_searches(DecisionTreeClassifier(), "DecisionTreeClassifier", 
                          grid, 
                          data_list_pca, "high_crime", 2020)

test year is: 2020
[2016, 2017, 2018, 2019]

In [11]:
tree_results.iloc[1]['parameters_2019']

{'criterion': 'gini',
 'max_depth': 1,
 'min_samples_split': 12,
 'random_state': 0}

In [10]:
tree_results.head(30)

,parameters_2019,precision_2019,parameters_2018,precision_2018,parameters_2017,precision_2017,mean
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.923605,0.945306

In [ ]:
tree_results_pca.head(30)

In [ ]:
tree_results.to_csv("../final_data/tree.csv")