### Decision Tree

#### Import Packages

In [1]:
%run ml_helpers.ipynb
%run ml.ipynb

       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
29557         108     1      1713        17       1  2018     1   First  1713
29558         109     1      1713        17       1  2018     1  Second  1713
29559         110     1      1713        17       1  2018     1   Third  1713
29560         111     1      1713        17       1  2018     2   Third  1713
29561         112     1      1713        17       1  2018     2   First  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
49256       59052     1       312         3       1  2019    11  Second   312
49257       59053     1       312         3       1  2019    11   Third   312
49258       59054     1       312         3       1  2019    12  Second   312
49259       59055     1       312         3       1  2019    12   First   312
49260       59056     1       312         3       1  2019    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
29557       8  ...               63.0         9.0             6.0
29558      16  ...               63.0         9.0             6.0
29559      24  ...               63.0         9.0             6.0
29560      16  ...               63.0         9.0             6.0
29561       8  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
49256      43  ...               14.0         1.0             3.0
49257      28  ...               14.0         1.0             3.0
49258      33  ...               14.0         1.0             3.0
49259      19  ...               14.0         1.0             3.0
49260      31  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
29557                  1.0              92.0     169276.405792
29558                  1.0              92.0     169276.405792
29559                  1.0              92.0     169276.405792
29560                  1.0              92.0     169276.405792
29561                  1.0              92.0     169276.405792
...                    ...               ...               ...
49256                  1.0              38.0     200633.844449
49257                  1.0              38.0     200633.844449
49258                  1.0              38.0     200633.844449
49259                  1.0              38.0     200633.844449
49260                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
29557      13283.675264    5454.068890       3258.006066             0.231076
29558      13283.675264    5454.068890       3258.006066             0.231076
29559      13283.675264    5454.068890       3258.006066             0.231076
29560      13283.675264    5454.068890       3258.006066             0.231076
29561      13283.675264    5454.068890       3258.006066             0.231076
...                 ...            ...               ...                  ...
49256       4144.689546    4843.037238       4374.482421             0.174216
49257       4144.689546    4843.037238       4374.482421             0.174216
49258       4144.689546    4843.037238       4374.482421             0.170732
49259       4144.689546    4843.037238       4374.482421             0.174216
49260       4144.689546    4843.037238       4374.482421             0.174216

[19704 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
19712          72     1      1713        17       1  2017     1   First  1713
19713          73     1      1713        17       1  2017     1   Third  1713
19714          74     1      1713        17       1  2017     1  Second  1713
19715          75     1      1713        17       1  2017     2  Second  1713
19716          76     1      1713        17       1  2017     2   Third  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
39402       59016     1       312         3       1  2018    11   Third   312
39403       59017     1       312         3       1  2018    11   First   312
39404       59018     1       312         3       1  2018    12   First   312
39405       59019     1       312         3       1  2018    12  Second   312
39406       59020     1       312         3       1  2018    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
19712      17  ...               63.0         9.0             6.0
19713      23  ...               63.0         9.0             6.0
19714      17  ...               63.0         9.0             6.0
19715      10  ...               63.0         9.0             6.0
19716      19  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
39402      33  ...               14.0         1.0             3.0
39403      12  ...               14.0         1.0             3.0
39404      15  ...               14.0         1.0             3.0
39405      36  ...               14.0         1.0             3.0
39406      34  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
19712                  1.0              92.0     169276.405792
19713                  1.0              92.0     169276.405792
19714                  1.0              92.0     169276.405792
19715                  1.0              92.0     169276.405792
19716                  1.0              92.0     169276.405792
...                    ...               ...               ...
39402                  1.0              38.0     200633.844449
39403                  1.0              38.0     200633.844449
39404                  1.0              38.0     200633.844449
39405                  1.0              38.0     200633.844449
39406                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
19712      13283.675264    5454.068890       3258.006066             0.243028
19713      13283.675264    5454.068890       3258.006066             0.243028
19714      13283.675264    5454.068890       3258.006066             0.243028
19715      13283.675264    5454.068890       3258.006066             0.243028
19716      13283.675264    5454.068890       3258.006066             0.243028
...                 ...            ...               ...                  ...
39402       4144.689546    4843.037238       4374.482421             0.104530
39403       4144.689546    4843.037238       4374.482421             0.104530
39404       4144.689546    4843.037238       4374.482421             0.104530
39405       4144.689546    4843.037238       4374.482421             0.101045
39406       4144.689546    4843.037238       4374.482421             0.104530

[19695 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
9861           36     1      1713        17       1  2016     1  Second  1713
9862           37     1      1713        17       1  2016     1   Third  1713
9863           38     1      1713        17       1  2016     1   First  1713
9864           39     1      1713        17       1  2016     2   First  1713
9865           40     1      1713        17       1  2016     2  Second  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
29552       58980     1       312         3       1  2017    11  Second   312
29553       58981     1       312         3       1  2017    11   Third   312
29554       58982     1       312         3       1  2017    12  Second   312
29555       58983     1       312         3       1  2017    12   Third   312
29556       58984     1       312         3       1  2017    12   First   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
9861       20  ...               63.0         9.0             6.0
9862       18  ...               63.0         9.0             6.0
9863        8  ...               63.0         9.0             6.0
9864        9  ...               63.0         9.0             6.0
9865       21  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
29552      45  ...               14.0         1.0             3.0
29553      35  ...               14.0         1.0             3.0
29554      29  ...               14.0         1.0             3.0
29555      42  ...               14.0         1.0             3.0
29556      22  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
9861                   1.0              92.0     169276.405792
9862                   1.0              92.0     169276.405792
9863                   1.0              92.0     169276.405792
9864                   1.0              92.0     169276.405792
9865                   1.0              92.0     169276.405792
...                    ...               ...               ...
29552                  1.0              38.0     200633.844449
29553                  1.0              38.0     200633.844449
29554                  1.0              38.0     200633.844449
29555                  1.0              38.0     200633.844449
29556                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
9861       13283.675264    5454.068890       3258.006066             0.167331
9862       13283.675264    5454.068890       3258.006066             0.167331
9863       13283.675264    5454.068890       3258.006066             0.167331
9864       13283.675264    5454.068890       3258.006066             0.167331
9865       13283.675264    5454.068890       3258.006066             0.167331
...                 ...            ...               ...                  ...
29552       4144.689546    4843.037238       4374.482421             0.135889
29553       4144.689546    4843.037238       4374.482421             0.139373
29554       4144.689546    4843.037238       4374.482421             0.139373
29555       4144.689546    4843.037238       4374.482421             0.139373
29556       4144.689546    4843.037238       4374.482421             0.139373

[19696 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
0               0     1      1713        17       1  2015     1   Third  1713
1               1     1      1713        17       1  2015     1  Second  1713
2               2     1      1713        17       1  2015     1   First  1713
3               3     1      1713        17       1  2015     2  Second  1713
4               4     1      1713        17       1  2015     2   Third  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
19707       58944     1       312         3       1  2016    11   First   312
19708       58945     1       312         3       1  2016    11  Second   312
19709       58946     1       312         3       1  2016    12   First   312
19710       58947     1       312         3       1  2016    12  Second   312
19711       58948     1       312         3       1  2016    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
0          16  ...               63.0         9.0             6.0
1          20  ...               63.0         9.0             6.0
2          14  ...               63.0         9.0             6.0
3          12  ...               63.0         9.0             6.0
4          12  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
19707      11  ...               14.0         1.0             3.0
19708      40  ...               14.0         1.0             3.0
19709      17  ...               14.0         1.0             3.0
19710      39  ...               14.0         1.0             3.0
19711      42  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
0                      1.0              92.0     169276.405792
1                      1.0              92.0     169276.405792
2                      1.0              92.0     169276.405792
3                      1.0              92.0     169276.405792
4                      1.0              92.0     169276.405792
...                    ...               ...               ...
19707                  1.0              38.0     200633.844449
19708                  1.0              38.0     200633.844449
19709                  1.0              38.0     200633.844449
19710                  1.0              38.0     200633.844449
19711                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
0          13283.675264    5454.068890       3258.006066             0.155378
1          13283.675264    5454.068890       3258.006066             0.155378
2          13283.675264    5454.068890       3258.006066             0.155378
3          13283.675264    5454.068890       3258.006066             0.155378
4          13283.675264    5454.068890       3258.006066             0.155378
...                 ...            ...               ...                  ...
19707       4144.689546    4843.037238       4374.482421             0.156794
19708       4144.689546    4843.037238       4374.482421             0.156794
19709       4144.689546    4843.037238       4374.482421             0.156794
19710       4144.689546    4843.037238       4374.482421             0.153310
19711       4144.689546    4843.037238       4374.482421             0.153310

[19712 rows x 31 columns]
Finished splitting...
Working on: [2017 2018]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.852368
1    0.852368
2    0.852368
3    0.852368
4    0.852368
Name: principal component 1, dtype: float64
(19695, 2) (19695, 328)
Working on: [2016 2017]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.85269
1    0.85269
2    0.85269
3    0.85269
4    0.85269
Name: principal component 1, dtype: float64
(19696, 2) (19696, 328)
Working on: [2015 2016]
Have accessed train and test df...

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.856576
1    0.856576
2    0.856576
3    0.856576
4    0.856576
Name: principal component 1, dtype: float64
(19712, 2) (19712, 328)
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
29557         108     1      1713        17       1  2018     1   First  1713
29558         109     1      1713        17       1  2018     1  Second  1713
29559         110     1      1713        17       1  2018     1   Third  1713
29560         111     1      1713        17       1  2018     2   Third  1713
29561         112     1      1713        17       1  2018     2   First  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
49256       59052     1       312         3       1  2019    11  Second   312
49257       59053     1       312         3       1  2019    11   Third   312
49258       59054     1       312         3       1  2019    12  Second   312
49259       59055     1       312         3       1  2019    12   First   312
49260       59056     1       312         3       1  2019    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
29557       8  ...               63.0         9.0             6.0
29558      16  ...               63.0         9.0             6.0
29559      24  ...               63.0         9.0             6.0
29560      16  ...               63.0         9.0             6.0
29561       8  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
49256      43  ...               14.0         1.0             3.0
49257      28  ...               14.0         1.0             3.0
49258      33  ...               14.0         1.0             3.0
49259      19  ...               14.0         1.0             3.0
49260      31  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
29557                  1.0              92.0     169276.405792
29558                  1.0              92.0     169276.405792
29559                  1.0              92.0     169276.405792
29560                  1.0              92.0     169276.405792
29561                  1.0              92.0     169276.405792
...                    ...               ...               ...
49256                  1.0              38.0     200633.844449
49257                  1.0              38.0     200633.844449
49258                  1.0              38.0     200633.844449
49259                  1.0              38.0     200633.844449
49260                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
29557      13283.675264    5454.068890       3258.006066             0.231076
29558      13283.675264    5454.068890       3258.006066             0.231076
29559      13283.675264    5454.068890       3258.006066             0.231076
29560      13283.675264    5454.068890       3258.006066             0.231076
29561      13283.675264    5454.068890       3258.006066             0.231076
...                 ...            ...               ...                  ...
49256       4144.689546    4843.037238       4374.482421             0.174216
49257       4144.689546    4843.037238       4374.482421             0.174216
49258       4144.689546    4843.037238       4374.482421             0.170732
49259       4144.689546    4843.037238       4374.482421             0.174216
49260       4144.689546    4843.037238       4374.482421             0.174216

[19704 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
19712          72     1      1713        17       1  2017     1   First  1713
19713          73     1      1713        17       1  2017     1   Third  1713
19714          74     1      1713        17       1  2017     1  Second  1713
19715          75     1      1713        17       1  2017     2  Second  1713
19716          76     1      1713        17       1  2017     2   Third  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
39402       59016     1       312         3       1  2018    11   Third   312
39403       59017     1       312         3       1  2018    11   First   312
39404       59018     1       312         3       1  2018    12   First   312
39405       59019     1       312         3       1  2018    12  Second   312
39406       59020     1       312         3       1  2018    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
19712      17  ...               63.0         9.0             6.0
19713      23  ...               63.0         9.0             6.0
19714      17  ...               63.0         9.0             6.0
19715      10  ...               63.0         9.0             6.0
19716      19  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
39402      33  ...               14.0         1.0             3.0
39403      12  ...               14.0         1.0             3.0
39404      15  ...               14.0         1.0             3.0
39405      36  ...               14.0         1.0             3.0
39406      34  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
19712                  1.0              92.0     169276.405792
19713                  1.0              92.0     169276.405792
19714                  1.0              92.0     169276.405792
19715                  1.0              92.0     169276.405792
19716                  1.0              92.0     169276.405792
...                    ...               ...               ...
39402                  1.0              38.0     200633.844449
39403                  1.0              38.0     200633.844449
39404                  1.0              38.0     200633.844449
39405                  1.0              38.0     200633.844449
39406                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
19712      13283.675264    5454.068890       3258.006066             0.243028
19713      13283.675264    5454.068890       3258.006066             0.243028
19714      13283.675264    5454.068890       3258.006066             0.243028
19715      13283.675264    5454.068890       3258.006066             0.243028
19716      13283.675264    5454.068890       3258.006066             0.243028
...                 ...            ...               ...                  ...
39402       4144.689546    4843.037238       4374.482421             0.104530
39403       4144.689546    4843.037238       4374.482421             0.104530
39404       4144.689546    4843.037238       4374.482421             0.104530
39405       4144.689546    4843.037238       4374.482421             0.101045
39406       4144.689546    4843.037238       4374.482421             0.104530

[19695 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
9861           36     1      1713        17       1  2016     1  Second  1713
9862           37     1      1713        17       1  2016     1   Third  1713
9863           38     1      1713        17       1  2016     1   First  1713
9864           39     1      1713        17       1  2016     2   First  1713
9865           40     1      1713        17       1  2016     2  Second  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
29552       58980     1       312         3       1  2017    11  Second   312
29553       58981     1       312         3       1  2017    11   Third   312
29554       58982     1       312         3       1  2017    12  Second   312
29555       58983     1       312         3       1  2017    12   Third   312
29556       58984     1       312         3       1  2017    12   First   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
9861       20  ...               63.0         9.0             6.0
9862       18  ...               63.0         9.0             6.0
9863        8  ...               63.0         9.0             6.0
9864        9  ...               63.0         9.0             6.0
9865       21  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
29552      45  ...               14.0         1.0             3.0
29553      35  ...               14.0         1.0             3.0
29554      29  ...               14.0         1.0             3.0
29555      42  ...               14.0         1.0             3.0
29556      22  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
9861                   1.0              92.0     169276.405792
9862                   1.0              92.0     169276.405792
9863                   1.0              92.0     169276.405792
9864                   1.0              92.0     169276.405792
9865                   1.0              92.0     169276.405792
...                    ...               ...               ...
29552                  1.0              38.0     200633.844449
29553                  1.0              38.0     200633.844449
29554                  1.0              38.0     200633.844449
29555                  1.0              38.0     200633.844449
29556                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
9861       13283.675264    5454.068890       3258.006066             0.167331
9862       13283.675264    5454.068890       3258.006066             0.167331
9863       13283.675264    5454.068890       3258.006066             0.167331
9864       13283.675264    5454.068890       3258.006066             0.167331
9865       13283.675264    5454.068890       3258.006066             0.167331
...                 ...            ...               ...                  ...
29552       4144.689546    4843.037238       4374.482421             0.135889
29553       4144.689546    4843.037238       4374.482421             0.139373
29554       4144.689546    4843.037238       4374.482421             0.139373
29555       4144.689546    4843.037238       4374.482421             0.139373
29556       4144.689546    4843.037238       4374.482421             0.139373

[19696 rows x 31 columns]
       Unnamed: 0  beat  beat_num  district  sector  Year Month   Watch  Beat  \
0               0     1      1713        17       1  2015     1   Third  1713
1               1     1      1713        17       1  2015     1  Second  1713
2               2     1      1713        17       1  2015     1   First  1713
3               3     1      1713        17       1  2015     2  Second  1713
4               4     1      1713        17       1  2015     2   Third  1713
...           ...   ...       ...       ...     ...   ...   ...     ...   ...
19707       58944     1       312         3       1  2016    11   First   312
19708       58945     1       312         3       1  2016    11  Second   312
19709       58946     1       312         3       1  2016    12   First   312
19710       58947     1       312         3       1  2016    12  Second   312
19711       58948     1       312         3       1  2016    12   Third   312

       Crimes  ...  count_restaurants  count_bars  count_daycares  \
0          16  ...               63.0         9.0             6.0
1          20  ...               63.0         9.0             6.0
2          14  ...               63.0         9.0             6.0
3          12  ...               63.0         9.0             6.0
4          12  ...               63.0         9.0             6.0
...       ...  ...                ...         ...             ...
19707      11  ...               14.0         1.0             3.0
19708      40  ...               14.0         1.0             3.0
19709      17  ...               14.0         1.0             3.0
19710      39  ...               14.0         1.0             3.0
19711      42  ...               14.0         1.0             3.0

       count_entertainment  count_businesses  road_distance_ft  \
0                      1.0              92.0     169276.405792
1                      1.0              92.0     169276.405792
2                      1.0              92.0     169276.405792
3                      1.0              92.0     169276.405792
4                      1.0              92.0     169276.405792
...                    ...               ...               ...
19707                  1.0              38.0     200633.844449
19708                  1.0              38.0     200633.844449
19709                  1.0              38.0     200633.844449
19710                  1.0              38.0     200633.844449
19711                  1.0              38.0     200633.844449

       TOTAL POPULATION dist_to_police  dist_to_hospital  high_crime_geog_lag
0          13283.675264    5454.068890       3258.006066             0.155378
1          13283.675264    5454.068890       3258.006066             0.155378
2          13283.675264    5454.068890       3258.006066             0.155378
3          13283.675264    5454.068890       3258.006066             0.155378
4          13283.675264    5454.068890       3258.006066             0.155378
...                 ...            ...               ...                  ...
19707       4144.689546    4843.037238       4374.482421             0.156794
19708       4144.689546    4843.037238       4374.482421             0.156794
19709       4144.689546    4843.037238       4374.482421             0.156794
19710       4144.689546    4843.037238       4374.482421             0.153310
19711       4144.689546    4843.037238       4374.482421             0.153310

[19712 rows x 31 columns]
Finished splitting...
Working on: [2017 2018]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.852368
1    0.852368
2    0.852368
3    0.852368
4    0.852368
Name: principal component 1, dtype: float64
(19695, 2) (19695, 328)
Working on: [2016 2017]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.85269
1    0.85269
2    0.85269
3    0.85269
4    0.85269
Name: principal component 1, dtype: float64
(19696, 2) (19696, 328)
Working on: [2015 2016]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data

C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\series.py:4463: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-1-bc70820a9afc>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"]=df["Year"].astype("category")
C:\Users\dcarb\anaconda3\envs\geo_env\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.856576
1    0.856576
2    0.856576
3    0.856576
4    0.856576
Name: principal component 1, dtype: float64
(19712, 2) (19712, 328)
         Unnamed: 0  Beat  Year  Month   Watch  PRCP  SNOW  TMAX  TMIN  \
1100080     1100080   725  2019      2   Third  0.00   0.0    46    30
1108361     1108361   111  2019      2   Third  0.00   0.0    32    17
1147049     1147049  1533  2019      4   Third  0.03   0.0    66    47
1251619     1251619   233  2019      9  Second  0.00   0.0    79    57
1318587     1318587  1422  2019     12   Third  0.00   0.2    25    14
...             ...   ...   ...    ...     ...   ...   ...   ...   ...
1122537     1122537   414  2019      3  Second  0.02   0.0    46    37
1275389     1275389   414  2019     10   First  0.00   0.0    72    53
1265388     1265388  1524  2019      9  Second  0.00   0.0    80    65
1223658     1223658   813  2019      8   First  0.00   0.0    82    63
1239838     1239838   323  2019      8   Third  0.00   0.0    78    69

         count_l_stops  ...  count_restaurants  count_bars  count_daycares  \
1100080            1.0  ...               13.0         0.0             2.0
1108361            3.0  ...              127.0        73.0             0.0
1147049            1.0  ...               21.0         3.0             1.0
1251619            0.0  ...                8.0         2.0             1.0
1318587            0.0  ...               41.0         8.0             3.0
...                ...  ...                ...         ...             ...
1122537            0.0  ...               24.0         1.0             6.0
1275389            0.0  ...               24.0         1.0             6.0
1265388            0.0  ...               24.0         1.0             4.0
1223658            1.0  ...              138.0        45.0             5.0
1239838            0.0  ...               37.0         4.0             8.0

         count_entertainment  count_businesses  road_distance_ft  \
1100080                  0.0              24.0          0.457074
1108361                 20.0             278.0          0.247834
1147049                  0.0              53.0          0.449942
1251619                  1.0              22.0          0.928250
1318587                  1.0              74.0          0.640252
...                      ...               ...               ...
1122537                  1.0              81.0          0.962700
1275389                  1.0              81.0          0.962700
1265388                  0.0              41.0          0.547773
1223658                  1.0             207.0          1.551454
1239838                  1.0              55.0          0.819839

         TOTAL POPULATION  dist_to_police  dist_to_hospital  was_arrested
1100080       5168.646461        0.007154          0.028739           0.0
1108361       1830.562201        0.023780          0.010850           0.0
1147049       7038.112338        0.019818          0.013749           0.0
1251619       6174.993915        0.022685          0.009108           0.0
1318587      12025.393601        0.018463          0.015333           0.0
...                   ...             ...               ...           ...
1122537      11696.404888        0.034587          0.006471           0.0
1275389      11696.404888        0.034587          0.006471           0.0
1265388       6606.091846        0.018698          0.024720           0.0
1223658      21819.823082        0.033934          0.052171           0.0
1239838       7460.887096        0.008261          0.026222           0.0

[269 rows x 22 columns]
        Unnamed: 0  Beat  Year  Month   Watch  PRCP  SNOW  TMAX  TMIN  \
958681      958681  1214  2018      8   Third  0.00   0.0    88    69
846815      846815  1235  2018      3   First  0.00   0.0    40    25
819422      819422  1011  2018      1  Second  0.00   0.0    52    37
886701      886701  1413  2018      5  Second  0.00   0.0    82    57
949989      949989  1014  2018      7   First  0.00   0.0    82    68
...            ...   ...   ...    ...     ...   ...   ...   ...   ...
984580      984580  1814  2018      9  Second  0.59   0.0    88    73
918892      918892   331  2018      6   First  0.00   0.0    89    65
941314      941314   412  2018      7  Second  0.00   0.0    87    72
822568      822568   332  2018      1   First  0.00   0.0    44    31
915913      915913  1833  2018      6  Second  0.15   0.0    69    62

        count_l_stops  ...  count_restaurants  count_bars  count_daycares  \
958681            2.0  ...              117.0        83.0             2.0
846815            0.0  ...               61.0        19.0             2.0
819422            0.0  ...                8.0         0.0             1.0
886701            0.0  ...               29.0        13.0             4.0
949989            1.0  ...               14.0         0.0             2.0
...               ...  ...                ...         ...             ...
984580            0.0  ...               71.0        39.0            10.0
918892            0.0  ...               20.0         8.0             1.0
941314            0.0  ...               50.0         1.0            12.0
822568            0.0  ...               15.0         2.0             3.0
915913            1.0  ...              181.0       131.0             5.0

        count_entertainment  count_businesses  road_distance_ft  \
958681                 22.0             333.0          0.752525
846815                  7.0             236.0          1.226774
819422                  0.0              28.0          0.608382
886701                  2.0              60.0          0.503178
949989                  0.0              39.0          0.388796
...                     ...               ...               ...
984580                  8.0             108.0          0.665584
918892                  2.0              46.0          1.064898
941314                  1.0             143.0          1.194758
822568                  1.0              45.0          0.400015
915913                 18.0             513.0          0.245779

        TOTAL POPULATION  dist_to_police  dist_to_hospital  was_arrested
958681       7287.624351        0.013750          0.026424           0.0
846815       9827.024353        0.010768          0.024754           0.0
819422       6950.898647        0.020399          0.019535           1.0
886701      10723.850072        0.014348          0.024282           1.0
949989       5637.559333        0.011615          0.020788           0.0
...                  ...             ...               ...           ...
984580      10335.656619        0.018172          0.016124           0.0
918892       8902.799662        0.030812          0.006801           1.0
941314      10123.086459        0.034260          0.017540           0.0
822568       6647.401609        0.022760          0.012327           1.0
915913       9567.655146        0.021362          0.003772           0.0

[262 rows x 22 columns]
        Unnamed: 0  Beat  Year  Month   Watch  PRCP  SNOW  TMAX  TMIN  \
605916      605916   734  2017      4   First  0.00   0.0    82    63
612891      612891   624  2017      4  Second  0.00   0.0    72    42
743063      743063  2534  2017     10   Third  0.00   0.0    80    56
780131      780131  2011  2017     11   Third  0.00   0.0    62    46
776554      776554  1113  2017     11   First  0.00   0.0    62    34
...            ...   ...   ...    ...     ...   ...   ...   ...   ...
656335      656335  2234  2017      6   First  0.19   0.0    80    59
702922      702922  1733  2017      8   First  0.15   0.0    84    73
648898      648898  1023  2017      6   Third  0.00   0.0    91    68
724330      724330  2011  2017      9  Second  0.00   0.0    81    59
723968      723968   133  2017      9   Third  0.05   0.0    76    64

        count_l_stops  ...  count_restaurants  count_bars  count_daycares  \
605916            0.0  ...                7.0         2.0             1.0
612891            0.0  ...               36.0         6.0             5.0
743063            0.0  ...               40.0         7.0             9.0
780131            0.0  ...               75.0        22.0             9.0
776554            1.0  ...               12.0         1.0             2.0
...               ...  ...                ...         ...             ...
656335            0.0  ...               25.0         4.0             2.0
702922            0.0  ...               70.0        23.0             2.0
648898            1.0  ...               36.0         4.0             1.0
724330            0.0  ...               75.0        22.0             9.0
723968            0.0  ...                5.0         1.0             1.0

        count_entertainment  count_businesses  road_distance_ft  \
605916                  1.0              21.0          0.463460
612891                  0.0             110.0          0.574488
743063                  1.0             119.0          0.558825
780131                  5.0             178.0          0.825366
776554                  1.0              44.0          0.465835
...                     ...               ...               ...
656335                  2.0              51.0          0.903273
702922                  3.0             143.0          0.943922
648898                  1.0              87.0          0.665213
724330                  5.0             178.0          0.825366
723968                  0.0              48.0          0.547783

        TOTAL POPULATION  dist_to_police  dist_to_hospital  was_arrested
605916       4391.423523        0.016567          0.030056           0.0
612891       8351.790851        0.012854          0.020856           1.0
743063      14027.159738        0.034701          0.022307           0.0
780131      17306.232909        0.006090          0.008332           0.0
776554       4161.746005        0.028441          0.021861           0.0
...                  ...             ...               ...           ...
656335       7798.227539        0.013132          0.031111           0.0
702922      12697.654319        0.025998          0.018718           0.0
648898       5246.686612        0.017345          0.004018           1.0
724330      17306.232909        0.006090          0.008332           0.0
723968       5619.141877        0.013416          0.004478           0.0

[258 rows x 22 columns]
        Unnamed: 0  Beat  Year  Month   Watch  PRCP  SNOW  TMAX  TMIN  \
460736      460736  1231  2016      9  Second  0.14   0.0    77    68
318618      318618   122  2016      3   Third  0.00   0.0    50    32
458381      458381   331  2016      9   First  0.00   0.0    82    63
504127      504127  1132  2016     11  Second  0.00   0.0    74    49
531041      531041  1421  2016     12   Third  0.00   0.0    32    26
...            ...   ...   ...    ...     ...   ...   ...   ...   ...
479642      479642  1831  2016     10   First  0.42   0.0    72    65
461118      461118  1651  2016      9   Third  0.14   0.0    77    68
294745      294745  1533  2016      2  Second  0.05   0.6    37    26
306149      306149  1712  2016      3  Second  0.03   0.4    39    23
286582      286582  1222  2016      2   Third  0.78   0.0    40    36

        count_l_stops  ...  count_restaurants  count_bars  count_daycares  \
460736            2.0  ...               71.0        18.0             2.0
318618            3.0  ...              383.0       100.0             1.0
458381            0.0  ...               20.0         8.0             1.0
504127            1.0  ...               22.0         0.0             0.0
531041            0.0  ...               34.0        10.0             4.0
...               ...  ...                ...         ...             ...
479642            1.0  ...              220.0       168.0             6.0
461118            0.0  ...                0.0         0.0             0.0
294745            1.0  ...               21.0         3.0             1.0
306149            0.0  ...              121.0        13.0             5.0
286582            2.0  ...               12.0         0.0             1.0

        count_entertainment  count_businesses  road_distance_ft  \
460736                  7.0              56.0          0.568027
318618                 16.0            1344.0          0.571604
458381                  2.0              46.0          1.064898
504127                  0.0              21.0          0.418567
531041                  0.0              57.0          0.541445
...                     ...               ...               ...
479642                 60.0             750.0          0.633247
461118                  0.0               0.0          0.076889
294745                  0.0              53.0          0.449942
306149                  3.0             218.0          1.588453
286582                  1.0              85.0          0.513818

        TOTAL POPULATION  dist_to_police  dist_to_hospital  was_arrested
460736       8750.451240        0.012836          0.004571           1.0
318618       1430.744007        0.023572          0.018381           0.0
458381       8902.799662        0.030812          0.006801           0.0
504127       4900.260383        0.022320          0.016078           0.0
531041      10800.892159        0.007922          0.013037           0.0
...                  ...             ...               ...           ...
479642       9746.448124        0.013669          0.014807           0.0
461118          0.000000        0.142355          0.094884           0.0
294745       7038.112338        0.019818          0.013749           0.0
306149      23032.305172        0.009735          0.030717           0.0
286582       3974.867968        0.014676          0.013009           0.0

[276 rows x 22 columns]
        Unnamed: 0  Beat  Year  Month   Watch  PRCP  SNOW  TMAX  TMIN  \
44146        44146  1724  2015      3   First  0.00   0.0    54    36
2146          2146   532  2015      1  Second  0.59   0.3    37    31
97420        97420  1011  2015      5   Third  0.00   0.0    68    50
230655      230655  1834  2015     11  Second  0.73   0.0    64    43
50347        50347  2534  2015      3  Second  0.00   0.0    50    41
...            ...   ...   ...    ...     ...   ...   ...   ...   ...
35783        35783  1812  2015      2  Second  0.18   4.0    22     7
147519      147519   234  2015      7  Second  0.00   0.0    82    71
57548        57548   414  2015      3   Third  0.03   0.0    51    28
98173        98173   213  2015      5   Third  0.00   0.0    83    53
56027        56027   623  2015      3   Third  0.04   0.6    34    25

        count_l_stops  ...  count_restaurants  count_bars  count_daycares  \
44146             0.0  ...               74.0        19.0             6.0
2146              0.0  ...               14.0         0.0             1.0
97420             0.0  ...                8.0         0.0             1.0
230655            1.0  ...              332.0       238.0             7.0
50347             0.0  ...               40.0         7.0             9.0
...               ...  ...                ...         ...             ...
35783             2.0  ...              119.0        48.0             5.0
147519            0.0  ...               84.0        30.0             4.0
57548             0.0  ...               24.0         1.0             6.0
98173             1.0  ...                7.0         4.0             2.0
56027             1.0  ...               42.0         3.0             6.0

        count_entertainment  count_businesses  road_distance_ft  \
44146                   5.0             183.0          0.676951
2146                    1.0              34.0          1.042029
97420                   0.0              28.0          0.608382
230655                 49.0             676.0          0.909764
50347                   1.0             119.0          0.558825
...                     ...               ...               ...
35783                  13.0             126.0          0.418606
147519                  6.0             149.0          0.396576
57548                   1.0              81.0          0.962700
98173                   2.0              31.0          0.647690
56027                   1.0              79.0          0.783098

        TOTAL POPULATION  dist_to_police  dist_to_hospital  was_arrested
44146       16356.526796        0.023527          0.011240           1.0
2146         5578.598700        0.021799          0.025951           0.0
97420        6950.898647        0.020399          0.019535           0.0
230655      16374.716120        0.029290          0.003678           0.0
50347       14027.159738        0.034701          0.022307           0.0
...                  ...             ...               ...           ...
35783        8365.503423        0.018854          0.003387           0.0
147519      10197.950015        0.036749          0.017948           1.0
57548       11696.404888        0.034587          0.006471           1.0
98173        4923.794671        0.007787          0.022774           0.0
56027        6759.295725        0.019789          0.027108           0.0

[263 rows x 22 columns]
Finished splitting...
Working on: [2018]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
Working on: [2017]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
Working on: [2016]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
Working on: [2015]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data

Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...

In [2]:
import pandas as pd
import geopandas as gpd
import seaborn as sns
import numpy as np
import sklearn as sk
from sklearn import preprocessing
from sklearn.pipeline import Pipeline
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import precision_score
import datetime

#### Read and Process Data

In [3]:
data = pd.read_csv("../intermediate_data/high_crime_labeled.csv")
data = data.drop(columns=["beat", "beat_num", "Crimes", "Arrest"])
data = convert_to_categorical(data, ["district", "sector",
                                    "Month",
                                     "Watch", "Beat"])
data.drop(columns = ["Unnamed: 0"], inplace=True)

#### Setup ML

In [4]:
models = {
    'DecisionTreeClassifier': DecisionTreeClassifier(), 
}
grid = {
    'DecisionTreeClassifier': [{'criterion': x, 'max_depth': y, 'min_samples_split':z, 'random_state': 0} 
                           for x in ('gini', 'entropy') \
                           for y in (1, 3, 5, 10, 15, 20, 30) \
                           for z in (2, 4, 6, 8, 10, 12, 13, 14, 15)
                              ]
}

In [5]:
data_list = prep_data(data, "high_crime",
                                        2, "Year", ["district", "sector", 
                                                    "Month", 
                                                    "Beat", "Watch"])

data_list_pca = prep_data(data, "high_crime",
                                        2, "Year", 
                          ["district", "sector", 
                                                    "Month", 
                                                    "Beat", "Watch"], pca="yes!", 
                                                  columns_to_pca = ["TOTAL POPULATION", "dist_to_police",
                                                                   "dist_to_hospital", 
                                                  "count_l_stops", "count_bus_stops", 
                                               "count_metra_stops", "count_restaurants", "count_bars", 
                                               "count_daycares", "count_entertainment", "count_businesses", 
                                               "road_distance_ft"])

      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
29557       17      1  2018     1   First  1713      1.0         2  33.201426
29558       17      1  2018     1  Second  1713      8.0         4  33.201426
29559       17      1  2018     1   Third  1713     11.0         4  33.201426
29560       17      1  2018     2   Third  1713      5.0         3  39.791635
29561       17      1  2018     2   First  1713      6.0         2  39.791635
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
49256        3      1  2019    11  Second   312     13.0        11  43.761013
49257        3      1  2019    11   Third   312     13.0         8  43.761013
49258        3      1  2019    12  Second   312     20.0         8  42.647269
49259        3      1  2019    12   First   312      7.0         8  42.647269
49260        3      1  2019    12   Third   312     13.0         4  42.647269

            TMIN  ...  count_restaurants  count_bars count_daycares  \
29557  18.884223  ...               63.0         9.0            6.0
29558  18.884223  ...               63.0         9.0            6.0
29559  18.884223  ...               63.0         9.0            6.0
29560  22.439919  ...               63.0         9.0            6.0
29561  22.439919  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
49256  29.648049  ...               14.0         1.0            3.0
49257  29.648049  ...               14.0         1.0            3.0
49258  27.854899  ...               14.0         1.0            3.0
49259  27.854899  ...               14.0         1.0            3.0
49260  27.854899  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
29557                  1.0              92.0     169276.405792
29558                  1.0              92.0     169276.405792
29559                  1.0              92.0     169276.405792
29560                  1.0              92.0     169276.405792
29561                  1.0              92.0     169276.405792
...                    ...               ...               ...
49256                  1.0              38.0     200633.844449
49257                  1.0              38.0     200633.844449
49258                  1.0              38.0     200633.844449
49259                  1.0              38.0     200633.844449
49260                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
29557      13283.675264     5454.068890       3258.006066             0.231076
29558      13283.675264     5454.068890       3258.006066             0.231076
29559      13283.675264     5454.068890       3258.006066             0.231076
29560      13283.675264     5454.068890       3258.006066             0.231076
29561      13283.675264     5454.068890       3258.006066             0.231076
...                 ...             ...               ...                  ...
49256       4144.689546     4843.037238       4374.482421             0.174216
49257       4144.689546     4843.037238       4374.482421             0.174216
49258       4144.689546     4843.037238       4374.482421             0.170732
49259       4144.689546     4843.037238       4374.482421             0.174216
49260       4144.689546     4843.037238       4374.482421             0.174216

[19704 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
19712       17      1  2017     1   First  1713      6.0         5  36.668219
19713       17      1  2017     1   Third  1713     16.0         4  36.668219
19714       17      1  2017     1  Second  1713     13.0         2  36.668219
19715       17      1  2017     2  Second  1713      7.0         2  48.828937
19716       17      1  2017     2   Third  1713      9.0         3  48.828937
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
39402        3      1  2018    11   Third   312     15.0         7  40.859811
39403        3      1  2018    11   First   312      7.0         4  40.859811
39404        3      1  2018    12   First   312      7.0         4  40.587445
39405        3      1  2018    12  Second   312     20.0        12  40.587445
39406        3      1  2018    12   Third   312     14.0         7  40.587445

            TMIN  ...  count_restaurants  count_bars count_daycares  \
19712  25.445660  ...               63.0         9.0            6.0
19713  25.445660  ...               63.0         9.0            6.0
19714  25.445660  ...               63.0         9.0            6.0
19715  30.957247  ...               63.0         9.0            6.0
19716  30.957247  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
39402  30.481732  ...               14.0         1.0            3.0
39403  30.481732  ...               14.0         1.0            3.0
39404  27.929352  ...               14.0         1.0            3.0
39405  27.929352  ...               14.0         1.0            3.0
39406  27.929352  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
19712                  1.0              92.0     169276.405792
19713                  1.0              92.0     169276.405792
19714                  1.0              92.0     169276.405792
19715                  1.0              92.0     169276.405792
19716                  1.0              92.0     169276.405792
...                    ...               ...               ...
39402                  1.0              38.0     200633.844449
39403                  1.0              38.0     200633.844449
39404                  1.0              38.0     200633.844449
39405                  1.0              38.0     200633.844449
39406                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
19712      13283.675264     5454.068890       3258.006066             0.243028
19713      13283.675264     5454.068890       3258.006066             0.243028
19714      13283.675264     5454.068890       3258.006066             0.243028
19715      13283.675264     5454.068890       3258.006066             0.243028
19716      13283.675264     5454.068890       3258.006066             0.243028
...                 ...             ...               ...                  ...
39402       4144.689546     4843.037238       4374.482421             0.104530
39403       4144.689546     4843.037238       4374.482421             0.104530
39404       4144.689546     4843.037238       4374.482421             0.104530
39405       4144.689546     4843.037238       4374.482421             0.101045
39406       4144.689546     4843.037238       4374.482421             0.104530

[19695 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
9861        17      1  2016     1  Second  1713     10.0         3  34.634797
9862        17      1  2016     1   Third  1713     11.0         4  34.634797
9863        17      1  2016     1   First  1713      2.0         4  34.634797
9864        17      1  2016     2   First  1713      5.0         0  39.873946
9865        17      1  2016     2  Second  1713     14.0         2  39.873946
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
29552        3      1  2017    11  Second   312     21.0        10  48.004051
29553        3      1  2017    11   Third   312     15.0         8  48.004051
29554        3      1  2017    12  Second   312      7.0         7  36.924981
29555        3      1  2017    12   Third   312     16.0        14  36.924981
29556        3      1  2017    12   First   312     11.0        11  36.924981

            TMIN  ...  count_restaurants  count_bars count_daycares  \
9861   21.333060  ...               63.0         9.0            6.0
9862   21.333060  ...               63.0         9.0            6.0
9863   21.333060  ...               63.0         9.0            6.0
9864   26.515109  ...               63.0         9.0            6.0
9865   26.515109  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
29552  33.954321  ...               14.0         1.0            3.0
29553  33.954321  ...               14.0         1.0            3.0
29554  23.299649  ...               14.0         1.0            3.0
29555  23.299649  ...               14.0         1.0            3.0
29556  23.299649  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
9861                   1.0              92.0     169276.405792
9862                   1.0              92.0     169276.405792
9863                   1.0              92.0     169276.405792
9864                   1.0              92.0     169276.405792
9865                   1.0              92.0     169276.405792
...                    ...               ...               ...
29552                  1.0              38.0     200633.844449
29553                  1.0              38.0     200633.844449
29554                  1.0              38.0     200633.844449
29555                  1.0              38.0     200633.844449
29556                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
9861       13283.675264     5454.068890       3258.006066             0.167331
9862       13283.675264     5454.068890       3258.006066             0.167331
9863       13283.675264     5454.068890       3258.006066             0.167331
9864       13283.675264     5454.068890       3258.006066             0.167331
9865       13283.675264     5454.068890       3258.006066             0.167331
...                 ...             ...               ...                  ...
29552       4144.689546     4843.037238       4374.482421             0.135889
29553       4144.689546     4843.037238       4374.482421             0.139373
29554       4144.689546     4843.037238       4374.482421             0.139373
29555       4144.689546     4843.037238       4374.482421             0.139373
29556       4144.689546     4843.037238       4374.482421             0.139373

[19696 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
0           17      1  2015     1   Third  1713     10.0         1  32.469987
1           17      1  2015     1  Second  1713     13.0         4  32.469987
2           17      1  2015     1   First  1713      5.0         3  32.469987
3           17      1  2015     2  Second  1713      7.0         1  26.455588
4           17      1  2015     2   Third  1713      5.0         3  26.455588
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
19707        3      1  2016    11   First   312      7.0         4  56.907539
19708        3      1  2016    11  Second   312     20.0         8  56.907539
19709        3      1  2016    12   First   312      8.0         4  33.189478
19710        3      1  2016    12  Second   312     20.0         8  33.189478
19711        3      1  2016    12   Third   312     21.0         4  33.189478

            TMIN  ...  count_restaurants  count_bars count_daycares  \
0      20.138549  ...               63.0         9.0            6.0
1      20.138549  ...               63.0         9.0            6.0
2      20.138549  ...               63.0         9.0            6.0
3      10.647633  ...               63.0         9.0            6.0
4      10.647633  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
19707  41.575555  ...               14.0         1.0            3.0
19708  41.575555  ...               14.0         1.0            3.0
19709  22.018894  ...               14.0         1.0            3.0
19710  22.018894  ...               14.0         1.0            3.0
19711  22.018894  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
0                      1.0              92.0     169276.405792
1                      1.0              92.0     169276.405792
2                      1.0              92.0     169276.405792
3                      1.0              92.0     169276.405792
4                      1.0              92.0     169276.405792
...                    ...               ...               ...
19707                  1.0              38.0     200633.844449
19708                  1.0              38.0     200633.844449
19709                  1.0              38.0     200633.844449
19710                  1.0              38.0     200633.844449
19711                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
0          13283.675264     5454.068890       3258.006066             0.155378
1          13283.675264     5454.068890       3258.006066             0.155378
2          13283.675264     5454.068890       3258.006066             0.155378
3          13283.675264     5454.068890       3258.006066             0.155378
4          13283.675264     5454.068890       3258.006066             0.155378
...                 ...             ...               ...                  ...
19707       4144.689546     4843.037238       4374.482421             0.156794
19708       4144.689546     4843.037238       4374.482421             0.156794
19709       4144.689546     4843.037238       4374.482421             0.156794
19710       4144.689546     4843.037238       4374.482421             0.153310
19711       4144.689546     4843.037238       4374.482421             0.153310

[19712 rows x 26 columns]
Finished splitting...
Working on: [2017 2018]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
Working on: [2016 2017]
Have accessed train and test df...

Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
Working on: [2015 2016]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
29557       17      1  2018     1   First  1713      1.0         2  33.201426
29558       17      1  2018     1  Second  1713      8.0         4  33.201426
29559       17      1  2018     1   Third  1713     11.0         4  33.201426
29560       17      1  2018     2   Third  1713      5.0         3  39.791635
29561       17      1  2018     2   First  1713      6.0         2  39.791635
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
49256        3      1  2019    11  Second   312     13.0        11  43.761013
49257        3      1  2019    11   Third   312     13.0         8  43.761013
49258        3      1  2019    12  Second   312     20.0         8  42.647269
49259        3      1  2019    12   First   312      7.0         8  42.647269
49260        3      1  2019    12   Third   312     13.0         4  42.647269

            TMIN  ...  count_restaurants  count_bars count_daycares  \
29557  18.884223  ...               63.0         9.0            6.0
29558  18.884223  ...               63.0         9.0            6.0
29559  18.884223  ...               63.0         9.0            6.0
29560  22.439919  ...               63.0         9.0            6.0
29561  22.439919  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
49256  29.648049  ...               14.0         1.0            3.0
49257  29.648049  ...               14.0         1.0            3.0
49258  27.854899  ...               14.0         1.0            3.0
49259  27.854899  ...               14.0         1.0            3.0
49260  27.854899  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
29557                  1.0              92.0     169276.405792
29558                  1.0              92.0     169276.405792
29559                  1.0              92.0     169276.405792
29560                  1.0              92.0     169276.405792
29561                  1.0              92.0     169276.405792
...                    ...               ...               ...
49256                  1.0              38.0     200633.844449
49257                  1.0              38.0     200633.844449
49258                  1.0              38.0     200633.844449
49259                  1.0              38.0     200633.844449
49260                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
29557      13283.675264     5454.068890       3258.006066             0.231076
29558      13283.675264     5454.068890       3258.006066             0.231076
29559      13283.675264     5454.068890       3258.006066             0.231076
29560      13283.675264     5454.068890       3258.006066             0.231076
29561      13283.675264     5454.068890       3258.006066             0.231076
...                 ...             ...               ...                  ...
49256       4144.689546     4843.037238       4374.482421             0.174216
49257       4144.689546     4843.037238       4374.482421             0.174216
49258       4144.689546     4843.037238       4374.482421             0.170732
49259       4144.689546     4843.037238       4374.482421             0.174216
49260       4144.689546     4843.037238       4374.482421             0.174216

[19704 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
19712       17      1  2017     1   First  1713      6.0         5  36.668219
19713       17      1  2017     1   Third  1713     16.0         4  36.668219
19714       17      1  2017     1  Second  1713     13.0         2  36.668219
19715       17      1  2017     2  Second  1713      7.0         2  48.828937
19716       17      1  2017     2   Third  1713      9.0         3  48.828937
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
39402        3      1  2018    11   Third   312     15.0         7  40.859811
39403        3      1  2018    11   First   312      7.0         4  40.859811
39404        3      1  2018    12   First   312      7.0         4  40.587445
39405        3      1  2018    12  Second   312     20.0        12  40.587445
39406        3      1  2018    12   Third   312     14.0         7  40.587445

            TMIN  ...  count_restaurants  count_bars count_daycares  \
19712  25.445660  ...               63.0         9.0            6.0
19713  25.445660  ...               63.0         9.0            6.0
19714  25.445660  ...               63.0         9.0            6.0
19715  30.957247  ...               63.0         9.0            6.0
19716  30.957247  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
39402  30.481732  ...               14.0         1.0            3.0
39403  30.481732  ...               14.0         1.0            3.0
39404  27.929352  ...               14.0         1.0            3.0
39405  27.929352  ...               14.0         1.0            3.0
39406  27.929352  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
19712                  1.0              92.0     169276.405792
19713                  1.0              92.0     169276.405792
19714                  1.0              92.0     169276.405792
19715                  1.0              92.0     169276.405792
19716                  1.0              92.0     169276.405792
...                    ...               ...               ...
39402                  1.0              38.0     200633.844449
39403                  1.0              38.0     200633.844449
39404                  1.0              38.0     200633.844449
39405                  1.0              38.0     200633.844449
39406                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
19712      13283.675264     5454.068890       3258.006066             0.243028
19713      13283.675264     5454.068890       3258.006066             0.243028
19714      13283.675264     5454.068890       3258.006066             0.243028
19715      13283.675264     5454.068890       3258.006066             0.243028
19716      13283.675264     5454.068890       3258.006066             0.243028
...                 ...             ...               ...                  ...
39402       4144.689546     4843.037238       4374.482421             0.104530
39403       4144.689546     4843.037238       4374.482421             0.104530
39404       4144.689546     4843.037238       4374.482421             0.104530
39405       4144.689546     4843.037238       4374.482421             0.101045
39406       4144.689546     4843.037238       4374.482421             0.104530

[19695 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
9861        17      1  2016     1  Second  1713     10.0         3  34.634797
9862        17      1  2016     1   Third  1713     11.0         4  34.634797
9863        17      1  2016     1   First  1713      2.0         4  34.634797
9864        17      1  2016     2   First  1713      5.0         0  39.873946
9865        17      1  2016     2  Second  1713     14.0         2  39.873946
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
29552        3      1  2017    11  Second   312     21.0        10  48.004051
29553        3      1  2017    11   Third   312     15.0         8  48.004051
29554        3      1  2017    12  Second   312      7.0         7  36.924981
29555        3      1  2017    12   Third   312     16.0        14  36.924981
29556        3      1  2017    12   First   312     11.0        11  36.924981

            TMIN  ...  count_restaurants  count_bars count_daycares  \
9861   21.333060  ...               63.0         9.0            6.0
9862   21.333060  ...               63.0         9.0            6.0
9863   21.333060  ...               63.0         9.0            6.0
9864   26.515109  ...               63.0         9.0            6.0
9865   26.515109  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
29552  33.954321  ...               14.0         1.0            3.0
29553  33.954321  ...               14.0         1.0            3.0
29554  23.299649  ...               14.0         1.0            3.0
29555  23.299649  ...               14.0         1.0            3.0
29556  23.299649  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
9861                   1.0              92.0     169276.405792
9862                   1.0              92.0     169276.405792
9863                   1.0              92.0     169276.405792
9864                   1.0              92.0     169276.405792
9865                   1.0              92.0     169276.405792
...                    ...               ...               ...
29552                  1.0              38.0     200633.844449
29553                  1.0              38.0     200633.844449
29554                  1.0              38.0     200633.844449
29555                  1.0              38.0     200633.844449
29556                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
9861       13283.675264     5454.068890       3258.006066             0.167331
9862       13283.675264     5454.068890       3258.006066             0.167331
9863       13283.675264     5454.068890       3258.006066             0.167331
9864       13283.675264     5454.068890       3258.006066             0.167331
9865       13283.675264     5454.068890       3258.006066             0.167331
...                 ...             ...               ...                  ...
29552       4144.689546     4843.037238       4374.482421             0.135889
29553       4144.689546     4843.037238       4374.482421             0.139373
29554       4144.689546     4843.037238       4374.482421             0.139373
29555       4144.689546     4843.037238       4374.482421             0.139373
29556       4144.689546     4843.037238       4374.482421             0.139373

[19696 rows x 26 columns]
      district sector  Year Month   Watch  Beat  Serious  Domestic       TMAX  \
0           17      1  2015     1   Third  1713     10.0         1  32.469987
1           17      1  2015     1  Second  1713     13.0         4  32.469987
2           17      1  2015     1   First  1713      5.0         3  32.469987
3           17      1  2015     2  Second  1713      7.0         1  26.455588
4           17      1  2015     2   Third  1713      5.0         3  26.455588
...        ...    ...   ...   ...     ...   ...      ...       ...        ...
19707        3      1  2016    11   First   312      7.0         4  56.907539
19708        3      1  2016    11  Second   312     20.0         8  56.907539
19709        3      1  2016    12   First   312      8.0         4  33.189478
19710        3      1  2016    12  Second   312     20.0         8  33.189478
19711        3      1  2016    12   Third   312     21.0         4  33.189478

            TMIN  ...  count_restaurants  count_bars count_daycares  \
0      20.138549  ...               63.0         9.0            6.0
1      20.138549  ...               63.0         9.0            6.0
2      20.138549  ...               63.0         9.0            6.0
3      10.647633  ...               63.0         9.0            6.0
4      10.647633  ...               63.0         9.0            6.0
...          ...  ...                ...         ...            ...
19707  41.575555  ...               14.0         1.0            3.0
19708  41.575555  ...               14.0         1.0            3.0
19709  22.018894  ...               14.0         1.0            3.0
19710  22.018894  ...               14.0         1.0            3.0
19711  22.018894  ...               14.0         1.0            3.0

       count_entertainment  count_businesses  road_distance_ft  \
0                      1.0              92.0     169276.405792
1                      1.0              92.0     169276.405792
2                      1.0              92.0     169276.405792
3                      1.0              92.0     169276.405792
4                      1.0              92.0     169276.405792
...                    ...               ...               ...
19707                  1.0              38.0     200633.844449
19708                  1.0              38.0     200633.844449
19709                  1.0              38.0     200633.844449
19710                  1.0              38.0     200633.844449
19711                  1.0              38.0     200633.844449

       TOTAL POPULATION  dist_to_police  dist_to_hospital  high_crime_geog_lag
0          13283.675264     5454.068890       3258.006066             0.155378
1          13283.675264     5454.068890       3258.006066             0.155378
2          13283.675264     5454.068890       3258.006066             0.155378
3          13283.675264     5454.068890       3258.006066             0.155378
4          13283.675264     5454.068890       3258.006066             0.155378
...                 ...             ...               ...                  ...
19707       4144.689546     4843.037238       4374.482421             0.156794
19708       4144.689546     4843.037238       4374.482421             0.156794
19709       4144.689546     4843.037238       4374.482421             0.156794
19710       4144.689546     4843.037238       4374.482421             0.153310
19711       4144.689546     4843.037238       4374.482421             0.153310

[19712 rows x 26 columns]
Finished splitting...
Working on: [2017 2018]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...

Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.852368
1    0.852368
2    0.852368
3    0.852368
4    0.852368
Name: principal component 1, dtype: float64
(19695, 2) (19695, 324)
Working on: [2016 2017]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.85269
1    0.85269
2    0.85269
3    0.85269
4    0.85269
Name: principal component 1, dtype: float64
(19696, 2) (19696, 324)
Working on: [2015 2016]
Have accessed train and test df...
Finished filling NAs with mean...
On to normalizing continuous...
Finished normalizing training data
Finished normalizing test data...
Finished one-hot encoding...
Finished one-hot encoding...
Finished standardizing...
0    0.856576
1    0.856576
2    0.856576
3    0.856576
4    0.856576
Name: principal component 1, dtype: float64
(19712, 2) (19712, 324)

In [6]:
tree_results = average_grid_searches(DecisionTreeClassifier(), "DecisionTreeClassifier", 
                          grid, 
                          data_list, "high_crime", 2020)

test year is: 2020
[2016, 2017, 2018, 2019]

In [7]:
tree_results_pca = average_grid_searches(DecisionTreeClassifier(), "DecisionTreeClassifier", 
                          grid, 
                          data_list_pca, "high_crime", 2020)

test year is: 2020
[2016, 2017, 2018, 2019]

In [12]:
tree_results.head(30)

,parameters_2019,precision_2019,parameters_2018,precision_2018,parameters_2017,precision_2017,mean
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967825,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.939789,0.953711
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.923605,0.945306
0,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.943745,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.968567,"{'criterion': 'gini', 'max_depth': 15, 'min_sa...",0.923605,0.945306

In [11]:
tree_results_pca.head(30)

,parameters_2019,precision_2019,parameters_2018,precision_2018,parameters_2017,precision_2017,mean
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",1.000000,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.979186,"{'criterion': 'gini', 'max_depth': 1, 'min_sam...",0.912357,0.963848
0,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.954833,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.958644,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.951802,0.955093
0,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.954833,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.958644,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.951802,0.955093
0,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.954833,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.958644,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.951802,0.955093
0,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.954833,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.958644,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.951802,0.955093
0,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.954833,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.958644,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.951802,0.955093
0,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.954833,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.958644,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.951802,0.955093
0,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.954833,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.958644,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.951802,0.955093
0,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.954833,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.958644,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.951802,0.955093
0,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.954833,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.958644,"{'criterion': 'entropy', 'max_depth': 5, 'min_...",0.951802,0.955093
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967448,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.940541,0.953836
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967448,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.940541,0.953836
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967448,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.940541,0.953836
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967448,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.940541,0.953836
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967448,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.940541,0.953836
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967448,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.940541,0.953836
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967448,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.940541,0.953836
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967448,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.940541,0.953836
0,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.953519,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.967448,"{'criterion': 'gini', 'max_depth': 5, 'min_sam...",0.940541,0.953836
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.954018,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968763,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.920396,0.947726
0,"{'criterion': 'gini', 'max_depth': 30, 'min_sa...",0.954018,"{'criterion': 'gini', 'max_depth': 30, 'min_sa...",0.968763,"{'criterion': 'gini', 'max_depth': 30, 'min_sa...",0.920396,0.947726
0,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.954018,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.968763,"{'criterion': 'gini', 'max_depth': 20, 'min_sa...",0.920396,0.947726

In [10]:
tree_results.to_csv("../final_data/tree.csv")